<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: /mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Observable/NRE_Observable.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_9761b53e3d9349800c0cb59b71c8cd3d.php">Utility</a></li><li class="navelem"><a class="el" href="dir_a403dfa1c90bb53ae27abfcf2bdf816c.php">Observable</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Observable.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___observable_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;vector&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;algorithm&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../Observer/NRE_Observer.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &quot;../Vector/NRE_Vector.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_utility.php">Utility</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_observable.php">   33</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <span class="keywordtype">bool</span> changed;                 </div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    <a class="code" href="class_n_r_e_1_1_utility_1_1_vector.php">Vector&lt;Observer*&gt;</a> observers;  </div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a>();</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> <span class="keyword">const</span>&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a0c1f5eb43b26526d963b8f354d6efefd">~Observable</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a1710c29e14429e62216cec550183fb17">isChanged</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ac57384199059d8393992578bbc6b9b34">add</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a>* o);</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                        <span class="keywordtype">void</span> <span class="keyword">remove</span>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a>* o);</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a3f8a1f4ed189c374fd0d65c28ab77652">clear</a>();</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                        std::size_t <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#aaf7e6162bd3de804c78a8991cce55603">getCount</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ae53ec28846ac7a5bf311dfe2fc9893bf">notifyAll</a>(<span class="keywordtype">void</span>* arg = 0);</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                    <span class="comment">//## Access Operator ##//</span></div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Vector&lt;Observer*&gt;::Iterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a3e9dac8ffe51ab4d3ab84f1aba171972">begin</a>();</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Vector&lt;Observer*&gt;::ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a3e9dac8ffe51ab4d3ab84f1aba171972">begin</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Vector&lt;Observer*&gt;::ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a41849f851c583c30937cf5ff2dd773c1">cbegin</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Vector&lt;Observer*&gt;::Iterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ac6b6f7fcda71c9a685432175e078f53f">end</a>();</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Vector&lt;Observer*&gt;::ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ac6b6f7fcda71c9a685432175e078f53f">end</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Vector&lt;Observer*&gt;::ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#af99f491c047eccba5d6b21dd9c255bc0">cend</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> <span class="keyword">const</span>&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;                <span class="keyword">protected</span>: <span class="comment">// Methods</span></div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;<span class="comment"></span>                    <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ad95320e70b7fd3ffe2406423c6eab9fa">setChanged</a>(<span class="keywordtype">bool</span> state);</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;            };</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;        }</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;    }</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;<span class="preprocessor">    #include &quot;NRE_Observable.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a3f8a1f4ed189c374fd0d65c28ab77652"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a3f8a1f4ed189c374fd0d65c28ab77652">NRE::Utility::Observable::clear</a></div><div class="ttdeci">void clear()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a41849f851c583c30937cf5ff2dd773c1"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a41849f851c583c30937cf5ff2dd773c1">NRE::Utility::Observable::cbegin</a></div><div class="ttdeci">Vector&lt; Observer * &gt;::ConstIterator cbegin() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ac57384199059d8393992578bbc6b9b34"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ac57384199059d8393992578bbc6b9b34">NRE::Utility::Observable::add</a></div><div class="ttdeci">void add(Observer *o)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a3e9dac8ffe51ab4d3ab84f1aba171972"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a3e9dac8ffe51ab4d3ab84f1aba171972">NRE::Utility::Observable::begin</a></div><div class="ttdeci">Vector&lt; Observer * &gt;::Iterator begin()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php">NRE::Utility::Observable</a></div><div class="ttdoc">Describe an observable object, coupled with observer. </div><div class="ttdef"><b>Definition:</b> NRE_Observable.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ae53ec28846ac7a5bf311dfe2fc9893bf"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ae53ec28846ac7a5bf311dfe2fc9893bf">NRE::Utility::Observable::notifyAll</a></div><div class="ttdeci">void notifyAll(void *arg=0)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a809470a00740d22093325490e0fe8bd2"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">NRE::Utility::Observable::Observable</a></div><div class="ttdeci">Observable()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_aaf7e6162bd3de804c78a8991cce55603"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#aaf7e6162bd3de804c78a8991cce55603">NRE::Utility::Observable::getCount</a></div><div class="ttdeci">std::size_t getCount() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a1710c29e14429e62216cec550183fb17"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a1710c29e14429e62216cec550183fb17">NRE::Utility::Observable::isChanged</a></div><div class="ttdeci">bool isChanged() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_af99f491c047eccba5d6b21dd9c255bc0"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#af99f491c047eccba5d6b21dd9c255bc0">NRE::Utility::Observable::cend</a></div><div class="ttdeci">Vector&lt; Observer * &gt;::ConstIterator cend() const </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ad95320e70b7fd3ffe2406423c6eab9fa"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ad95320e70b7fd3ffe2406423c6eab9fa">NRE::Utility::Observable::setChanged</a></div><div class="ttdeci">void setChanged(bool state)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observer_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observer.php">NRE::Utility::Observer</a></div><div class="ttdoc">Describe an observer object attached to an Observable. </div><div class="ttdef"><b>Definition:</b> NRE_Observer.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ac6b6f7fcda71c9a685432175e078f53f"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ac6b6f7fcda71c9a685432175e078f53f">NRE::Utility::Observable::end</a></div><div class="ttdeci">Vector&lt; Observer * &gt;::Iterator end()</div></div>
<div class="ttc" id="namespace_utility_php"><div class="ttname"><a href="namespace_utility.php">Utility</a></div><div class="ttdoc">Utility&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a0c1f5eb43b26526d963b8f354d6efefd"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a0c1f5eb43b26526d963b8f354d6efefd">NRE::Utility::Observable::~Observable</a></div><div class="ttdeci">virtual ~Observable()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_af2070c089e1fc97f47e9aca09999a23e"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">NRE::Utility::Observable::operator=</a></div><div class="ttdeci">Observable &amp; operator=(Observable const &amp;o)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_vector_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector</a></div><div class="ttdoc">A dynamic array, guarantee to be in contiguous memory. </div><div class="ttdef"><b>Definition:</b> NRE_Vector.hpp:34</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
