<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: /mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Stack/NRE_Stack.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_9761b53e3d9349800c0cb59b71c8cd3d.php">Utility</a></li><li class="navelem"><a class="el" href="dir_027a6a9c26a67af3aa24a0b6cd9ab3c9.php">Stack</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Stack.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;../Vector/NRE_Vector.hpp&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_utility.php">Utility</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;        </div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">class</span> Container = Vector&lt;T&gt;&gt;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_stack.php">   30</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stringable.php">Stringable</a>&lt;Stack&lt;T, Container&gt;&gt; {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                static_assert(std::is_same_v&lt;T, Container::ValueType&gt;);</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Traits</span></div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_stack.php#a5c743a548f840e6225b6a2d461c0aaf6">   34</a></span>&#160;<span class="comment"></span>                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a5c743a548f840e6225b6a2d461c0aaf6">ValueType</a>      = <span class="keyword">typename</span> Container::ValueType;</div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_stack.php#a99d83ddf49d4581d6f6a773bfeb0e5d0">   36</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a99d83ddf49d4581d6f6a773bfeb0e5d0">SizeType</a>       = <span class="keyword">typename</span> Container::SizeType;</div><div class="line"><a name="l00038"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_stack.php#a95e7b113a807277be45dcafc359ea816">   38</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a95e7b113a807277be45dcafc359ea816">Reference</a>      = <span class="keyword">typename</span> Container::Reference;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_stack.php#ad59f16a8f6f6d328ccbd93f1cc1efd68">   40</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ad59f16a8f6f6d328ccbd93f1cc1efd68">ConstReference</a> = <span class="keyword">typename</span> Container::ConstReference;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    </div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    Container c;    </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(Container &amp;&amp; container = Container());</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(Container <span class="keyword">const</span>&amp; container);</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;    </div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        </div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> &amp;&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        </div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#abde8678c62784d73239a488e6a16f8d3">~Stack</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;    </div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a95e7b113a807277be45dcafc359ea816">Reference</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ac09daa4d46eaa13cb01727d10f4e96ec">getTop</a>();</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ad59f16a8f6f6d328ccbd93f1cc1efd68">ConstReference</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ac09daa4d46eaa13cb01727d10f4e96ec">getTop</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ad2c84dfbe7f88a6c0350b400b593e251">isEmpty</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a99d83ddf49d4581d6f6a773bfeb0e5d0">SizeType</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aaaf303382042a72c3f6d9465c7a71133">getSize</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;        </div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ac0168b5cd5c9d1bcb562cea379db7ef6">push</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ad59f16a8f6f6d328ccbd93f1cc1efd68">ConstReference</a> value);</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ac0168b5cd5c9d1bcb562cea379db7ef6">push</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a5c743a548f840e6225b6a2d461c0aaf6">ValueType</a> &amp;&amp; value);</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class </span>... Args&gt;</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a7056eedccf0985dfc6b83811373765ae">emplace</a>(Args &amp;&amp; ... args);</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a27f8d9c497e05251326a49655bd9da48">pop</a>();</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aa7846ea11319d74378c03278fa5ac7b0">swap</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a>&amp; s);</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;    </div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> &amp;&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;        </div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;                    <span class="comment">//## Comparison Operator ##//</span></div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a39f4b130a39d707e1f26a6e1ae7911ea">operator ==</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) <span class="keyword">const</span>;</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ac3cd88146c5182ab3e876440c329ab31">operator !=</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) <span class="keyword">const</span>;</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;    </div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;<span class="comment"></span>                        [[nodiscard]] <a class="code" href="class_n_r_e_1_1_utility_1_1_basic_string.php">String</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a9259e7119a6d5a7c50770431379098b1">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;            };</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        }</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;    }</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;<span class="preprocessor">    #include &quot;NRE_Stack.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a99d83ddf49d4581d6f6a773bfeb0e5d0"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a99d83ddf49d4581d6f6a773bfeb0e5d0">NRE::Utility::Stack::SizeType</a></div><div class="ttdeci">typename Container::SizeType SizeType</div><div class="ttdef"><b>Definition:</b> NRE_Stack.hpp:36</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_abde8678c62784d73239a488e6a16f8d3"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#abde8678c62784d73239a488e6a16f8d3">NRE::Utility::Stack::~Stack</a></div><div class="ttdeci">~Stack()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a27f8d9c497e05251326a49655bd9da48"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a27f8d9c497e05251326a49655bd9da48">NRE::Utility::Stack::pop</a></div><div class="ttdeci">void pop()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_aaaf303382042a72c3f6d9465c7a71133"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#aaaf303382042a72c3f6d9465c7a71133">NRE::Utility::Stack::getSize</a></div><div class="ttdeci">SizeType getSize() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_aa0591770d9d6ffd0b3d20b91b7632030"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">NRE::Utility::Stack::operator=</a></div><div class="ttdeci">Stack &amp; operator=(Stack const &amp;s)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a95e7b113a807277be45dcafc359ea816"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a95e7b113a807277be45dcafc359ea816">NRE::Utility::Stack::Reference</a></div><div class="ttdeci">typename Container::Reference Reference</div><div class="ttdef"><b>Definition:</b> NRE_Stack.hpp:38</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a0fb9f26708174bd16ad33be23fa79b0b"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">NRE::Utility::Stack::Stack</a></div><div class="ttdeci">Stack(Container &amp;&amp;container=Container())</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack</a></div><div class="ttdoc">A stack adapter wrapping a container class. </div><div class="ttdef"><b>Definition:</b> NRE_Stack.hpp:30</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stringable_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stringable.php">NRE::Utility::Stringable</a></div><div class="ttdoc">Describe an stringable object. </div><div class="ttdef"><b>Definition:</b> NRE_Stringable.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ac0168b5cd5c9d1bcb562cea379db7ef6"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ac0168b5cd5c9d1bcb562cea379db7ef6">NRE::Utility::Stack::push</a></div><div class="ttdeci">void push(ConstReference value)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a5c743a548f840e6225b6a2d461c0aaf6"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a5c743a548f840e6225b6a2d461c0aaf6">NRE::Utility::Stack::ValueType</a></div><div class="ttdeci">typename Container::ValueType ValueType</div><div class="ttdef"><b>Definition:</b> NRE_Stack.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ac09daa4d46eaa13cb01727d10f4e96ec"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ac09daa4d46eaa13cb01727d10f4e96ec">NRE::Utility::Stack::getTop</a></div><div class="ttdeci">Reference getTop()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a7056eedccf0985dfc6b83811373765ae"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a7056eedccf0985dfc6b83811373765ae">NRE::Utility::Stack::emplace</a></div><div class="ttdeci">void emplace(Args &amp;&amp;...args)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ad2c84dfbe7f88a6c0350b400b593e251"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ad2c84dfbe7f88a6c0350b400b593e251">NRE::Utility::Stack::isEmpty</a></div><div class="ttdeci">bool isEmpty() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a39f4b130a39d707e1f26a6e1ae7911ea"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a39f4b130a39d707e1f26a6e1ae7911ea">NRE::Utility::Stack::operator==</a></div><div class="ttdeci">bool operator==(Stack const &amp;s) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a9259e7119a6d5a7c50770431379098b1"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a9259e7119a6d5a7c50770431379098b1">NRE::Utility::Stack::toString</a></div><div class="ttdeci">String toString() const </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_basic_string_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_basic_string.php">NRE::Utility::BasicString</a></div><div class="ttdoc">A basic template string, with dynamic size, guarantee to be in contiguous memory. ...</div><div class="ttdef"><b>Definition:</b> NRE_String.hpp:38</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_aa7846ea11319d74378c03278fa5ac7b0"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#aa7846ea11319d74378c03278fa5ac7b0">NRE::Utility::Stack::swap</a></div><div class="ttdeci">void swap(Stack &amp;s)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ac3cd88146c5182ab3e876440c329ab31"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ac3cd88146c5182ab3e876440c329ab31">NRE::Utility::Stack::operator!=</a></div><div class="ttdeci">bool operator!=(Stack const &amp;s) const </div></div>
<div class="ttc" id="namespace_utility_php"><div class="ttname"><a href="namespace_utility.php">Utility</a></div><div class="ttdoc">Utility&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ad59f16a8f6f6d328ccbd93f1cc1efd68"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ad59f16a8f6f6d328ccbd93f1cc1efd68">NRE::Utility::Stack::ConstReference</a></div><div class="ttdeci">typename Container::ConstReference ConstReference</div><div class="ttdef"><b>Definition:</b> NRE_Stack.hpp:40</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
