<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: /mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Observable/NRE_Observable.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_9761b53e3d9349800c0cb59b71c8cd3d.php">Utility</a></li><li class="navelem"><a class="el" href="dir_a403dfa1c90bb53ae27abfcf2bdf816c.php">Observable</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Observable.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___observable_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;vector&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;algorithm&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../Observer/NRE_Observer.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &quot;../Vector/NRE_Vector.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_utility.php">Utility</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_observable.php">   33</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">public</span>:     <span class="comment">//Traits</span></div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_observable.php#a7653496967f32e0e852c77dd18e2e48b">   36</a></span>&#160;<span class="comment"></span>                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php">Container</a>     = <a class="code" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php">Vector&lt;Observer*&gt;</a>;</div><div class="line"><a name="l00038"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">   38</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a>      = <span class="keyword">typename</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#aedc34798595924837f67fe06ae52dde7">Container::Iterator</a>;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">   40</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> = <span class="keyword">typename</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#afd29351c483eaf1b8b1322463b1ae11f">Container::ConstIterator</a>;</div><div class="line"><a name="l00042"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">   42</a></span>&#160;                    <span class="keyword">using</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">SizeType</a>      = <span class="keyword">typename</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#ab312674a156498a72bd5e4aca800b098">Container::SizeType</a>;</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    </div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    <span class="keywordtype">bool</span> changed;         </div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <a class="code" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php">Container</a> observers;  </div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a>();</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> <span class="keyword">const</span>&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a0c1f5eb43b26526d963b8f354d6efefd">~Observable</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a1710c29e14429e62216cec550183fb17">isChanged</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ac57384199059d8393992578bbc6b9b34">add</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a>* o);</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                        <span class="keywordtype">void</span> <span class="keyword">remove</span>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a>* o);</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a3f8a1f4ed189c374fd0d65c28ab77652">clear</a>();</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">SizeType</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a34e29f2813b4d466ebceecaecd5c6a05">getCount</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ae53ec28846ac7a5bf311dfe2fc9893bf">notifyAll</a>(<span class="keywordtype">void</span>* arg = 0);</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                    <span class="comment">//## Access Operator ##//</span></div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a1c9ededf87047f24fa5a7726f9612e26">begin</a>();</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a1c9ededf87047f24fa5a7726f9612e26">begin</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a42e2e119214b1bebc0c1eeec020bddd6">cbegin</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#afc048fdbf499f9ed0a3e5b00e9249891">end</a>();</div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#afc048fdbf499f9ed0a3e5b00e9249891">end</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#a9c013d58495e7b5aa03c0547361b7fc5">cend</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> <span class="keyword">const</span>&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp; o) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;                <span class="keyword">protected</span>: <span class="comment">// Methods</span></div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;<span class="comment"></span>                    <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_observable.php#ad95320e70b7fd3ffe2406423c6eab9fa">setChanged</a>(<span class="keywordtype">bool</span> state);</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;            };</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;        }</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;    }</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;<span class="preprocessor">    #include &quot;NRE_Observable.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a3f8a1f4ed189c374fd0d65c28ab77652"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a3f8a1f4ed189c374fd0d65c28ab77652">NRE::Utility::Observable::clear</a></div><div class="ttdeci">void clear()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ac57384199059d8393992578bbc6b9b34"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ac57384199059d8393992578bbc6b9b34">NRE::Utility::Observable::add</a></div><div class="ttdeci">void add(Observer *o)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a1c9ededf87047f24fa5a7726f9612e26"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a1c9ededf87047f24fa5a7726f9612e26">NRE::Utility::Observable::begin</a></div><div class="ttdeci">Iterator begin()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php">NRE::Utility::Observable</a></div><div class="ttdoc">Describe an observable object, coupled with observer. </div><div class="ttdef"><b>Definition:</b> NRE_Observable.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a42e2e119214b1bebc0c1eeec020bddd6"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a42e2e119214b1bebc0c1eeec020bddd6">NRE::Utility::Observable::cbegin</a></div><div class="ttdeci">ConstIterator cbegin() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ae53ec28846ac7a5bf311dfe2fc9893bf"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ae53ec28846ac7a5bf311dfe2fc9893bf">NRE::Utility::Observable::notifyAll</a></div><div class="ttdeci">void notifyAll(void *arg=0)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_detail_1_1_vector_php_afd29351c483eaf1b8b1322463b1ae11f"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#afd29351c483eaf1b8b1322463b1ae11f">NRE::Utility::Detail::Vector::ConstIterator</a></div><div class="ttdeci">ConstPointer ConstIterator</div><div class="ttdef"><b>Definition:</b> NRE_Vector.hpp:65</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a809470a00740d22093325490e0fe8bd2"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">NRE::Utility::Observable::Observable</a></div><div class="ttdeci">Observable()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a9c013d58495e7b5aa03c0547361b7fc5"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a9c013d58495e7b5aa03c0547361b7fc5">NRE::Utility::Observable::cend</a></div><div class="ttdeci">ConstIterator cend() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a1710c29e14429e62216cec550183fb17"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a1710c29e14429e62216cec550183fb17">NRE::Utility::Observable::isChanged</a></div><div class="ttdeci">bool isChanged() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a34e29f2813b4d466ebceecaecd5c6a05"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a34e29f2813b4d466ebceecaecd5c6a05">NRE::Utility::Observable::getCount</a></div><div class="ttdeci">SizeType getCount() const </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_ad95320e70b7fd3ffe2406423c6eab9fa"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#ad95320e70b7fd3ffe2406423c6eab9fa">NRE::Utility::Observable::setChanged</a></div><div class="ttdeci">void setChanged(bool state)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_acd5ae58a1df83250687e1c594460c3a9"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">NRE::Utility::Observable::ConstIterator</a></div><div class="ttdeci">typename Container::ConstIterator ConstIterator</div><div class="ttdef"><b>Definition:</b> NRE_Observable.hpp:40</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observer_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observer.php">NRE::Utility::Observer</a></div><div class="ttdoc">Describe an observer object attached to an Observable. </div><div class="ttdef"><b>Definition:</b> NRE_Observer.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_afc048fdbf499f9ed0a3e5b00e9249891"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#afc048fdbf499f9ed0a3e5b00e9249891">NRE::Utility::Observable::end</a></div><div class="ttdeci">Iterator end()</div></div>
<div class="ttc" id="namespace_utility_php"><div class="ttname"><a href="namespace_utility.php">Utility</a></div><div class="ttdoc">Utility&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a429d9cdc5bb4b232e75a727676be02bf"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">NRE::Utility::Observable::Iterator</a></div><div class="ttdeci">typename Container::Iterator Iterator</div><div class="ttdef"><b>Definition:</b> NRE_Observable.hpp:38</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_detail_1_1_vector_php_ab312674a156498a72bd5e4aca800b098"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#ab312674a156498a72bd5e4aca800b098">NRE::Utility::Detail::Vector::SizeType</a></div><div class="ttdeci">std::size_t SizeType</div><div class="ttdef"><b>Definition:</b> NRE_Vector.hpp:51</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a0c1f5eb43b26526d963b8f354d6efefd"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a0c1f5eb43b26526d963b8f354d6efefd">NRE::Utility::Observable::~Observable</a></div><div class="ttdeci">virtual ~Observable()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_detail_1_1_vector_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php">NRE::Utility::Detail::Vector</a></div><div class="ttdoc">A dynamic array, guarantee to be in contiguous memory. </div><div class="ttdef"><b>Definition:</b> NRE_Vector.hpp:41</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_af2070c089e1fc97f47e9aca09999a23e"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">NRE::Utility::Observable::operator=</a></div><div class="ttdeci">Observable &amp; operator=(Observable const &amp;o)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_observable_php_a36ef23c9392524b4f64718505a870760"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">NRE::Utility::Observable::SizeType</a></div><div class="ttdeci">typename Container::SizeType SizeType</div><div class="ttdef"><b>Definition:</b> NRE_Observable.hpp:42</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_detail_1_1_vector_php_aedc34798595924837f67fe06ae52dde7"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#aedc34798595924837f67fe06ae52dde7">NRE::Utility::Detail::Vector::Iterator</a></div><div class="ttdeci">Pointer Iterator</div><div class="ttdef"><b>Definition:</b> NRE_Vector.hpp:63</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
