<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: /mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Stack/NRE_Stack.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_9761b53e3d9349800c0cb59b71c8cd3d.php">Utility</a></li><li class="navelem"><a class="el" href="dir_027a6a9c26a67af3aa24a0b6cd9ab3c9.php">Stack</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Stack.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;../Vector/NRE_Vector.hpp&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_utility.php">Utility</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;        </div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keyword">class</span> Container = Vector&lt;T&gt;&gt;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_stack.php">   30</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stringable.php">Stringable</a>&lt;Stack&lt;T, Container&gt;&gt; {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                    Container c;    </div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(Container &amp;&amp; container = Container());</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(Container <span class="keyword">const</span>&amp; container);</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;    </div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        </div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> &amp;&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;        </div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#abde8678c62784d73239a488e6a16f8d3">~Stack</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;    </div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="comment"></span>                        T&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#abd7056182ae176012d9f55cedf427813">getTop</a>();</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                        T <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#abd7056182ae176012d9f55cedf427813">getTop</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ad2c84dfbe7f88a6c0350b400b593e251">isEmpty</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                        std::size_t <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a41619ddba878602b48c277facb3e2e11">getSize</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        </div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a4cf97be0bf934c70ead58c5fef7853aa">push</a>(T <span class="keyword">const</span>&amp; value);</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a4cf97be0bf934c70ead58c5fef7853aa">push</a>(T &amp;&amp; value);</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class </span>... Args&gt;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a7056eedccf0985dfc6b83811373765ae">emplace</a>(Args &amp;&amp; ... args);</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a27f8d9c497e05251326a49655bd9da48">pop</a>();</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aa7846ea11319d74378c03278fa5ac7b0">swap</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a>&amp; s);</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;    </div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;                        <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">operator =</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> &amp;&amp; s) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;        </div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                    <span class="comment">//## Comparison Operator ##//</span></div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a39f4b130a39d707e1f26a6e1ae7911ea">operator ==</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) <span class="keyword">const</span>;</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#ac3cd88146c5182ab3e876440c329ab31">operator !=</a>(<a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a> <span class="keyword">const</span>&amp; s) <span class="keyword">const</span>;</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;    </div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_utility_1_1_basic_string.php">String</a> <a class="code" href="class_n_r_e_1_1_utility_1_1_stack.php#a9259e7119a6d5a7c50770431379098b1">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;            };</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        }</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    }</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;<span class="preprocessor">    #include &quot;NRE_Stack.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_abde8678c62784d73239a488e6a16f8d3"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#abde8678c62784d73239a488e6a16f8d3">NRE::Utility::Stack::~Stack</a></div><div class="ttdeci">~Stack()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a27f8d9c497e05251326a49655bd9da48"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a27f8d9c497e05251326a49655bd9da48">NRE::Utility::Stack::pop</a></div><div class="ttdeci">void pop()</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_aa0591770d9d6ffd0b3d20b91b7632030"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">NRE::Utility::Stack::operator=</a></div><div class="ttdeci">Stack &amp; operator=(Stack const &amp;s)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a0fb9f26708174bd16ad33be23fa79b0b"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">NRE::Utility::Stack::Stack</a></div><div class="ttdeci">Stack(Container &amp;&amp;container=Container())</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack</a></div><div class="ttdoc">A stack adapter wrapping a container class. </div><div class="ttdef"><b>Definition:</b> NRE_Stack.hpp:30</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stringable_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stringable.php">NRE::Utility::Stringable</a></div><div class="ttdoc">Describe an stringable object. </div><div class="ttdef"><b>Definition:</b> NRE_Stringable.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a41619ddba878602b48c277facb3e2e11"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a41619ddba878602b48c277facb3e2e11">NRE::Utility::Stack::getSize</a></div><div class="ttdeci">std::size_t getSize() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a7056eedccf0985dfc6b83811373765ae"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a7056eedccf0985dfc6b83811373765ae">NRE::Utility::Stack::emplace</a></div><div class="ttdeci">void emplace(Args &amp;&amp;...args)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ad2c84dfbe7f88a6c0350b400b593e251"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ad2c84dfbe7f88a6c0350b400b593e251">NRE::Utility::Stack::isEmpty</a></div><div class="ttdeci">bool isEmpty() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a39f4b130a39d707e1f26a6e1ae7911ea"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a39f4b130a39d707e1f26a6e1ae7911ea">NRE::Utility::Stack::operator==</a></div><div class="ttdeci">bool operator==(Stack const &amp;s) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a9259e7119a6d5a7c50770431379098b1"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a9259e7119a6d5a7c50770431379098b1">NRE::Utility::Stack::toString</a></div><div class="ttdeci">String toString() const </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_basic_string_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_basic_string.php">NRE::Utility::BasicString</a></div><div class="ttdoc">A basic template string, with dynamic size, guarantee to be in contiguous memory. ...</div><div class="ttdef"><b>Definition:</b> NRE_String.hpp:38</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_aa7846ea11319d74378c03278fa5ac7b0"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#aa7846ea11319d74378c03278fa5ac7b0">NRE::Utility::Stack::swap</a></div><div class="ttdeci">void swap(Stack &amp;s)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_ac3cd88146c5182ab3e876440c329ab31"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#ac3cd88146c5182ab3e876440c329ab31">NRE::Utility::Stack::operator!=</a></div><div class="ttdeci">bool operator!=(Stack const &amp;s) const </div></div>
<div class="ttc" id="namespace_utility_php"><div class="ttname"><a href="namespace_utility.php">Utility</a></div><div class="ttdoc">Utility&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_a4cf97be0bf934c70ead58c5fef7853aa"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#a4cf97be0bf934c70ead58c5fef7853aa">NRE::Utility::Stack::push</a></div><div class="ttdeci">void push(T const &amp;value)</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_stack_php_abd7056182ae176012d9f55cedf427813"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_stack.php#abd7056182ae176012d9f55cedf427813">NRE::Utility::Stack::getTop</a></div><div class="ttdeci">T &amp; getTop()</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
