<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: /mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Interfaces/NRE_StaticInterface.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_9761b53e3d9349800c0cb59b71c8cd3d.php">Utility</a></li><li class="navelem"><a class="el" href="dir_b7017f46de0d068332e4c2d3bf7ed59e.php">Interfaces</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_StaticInterface.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___static_interface_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;    </div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;    </div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_utility.php">Utility</a> {</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;            </div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00028"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_static_interface.php">   28</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_utility_1_1_static_interface.php">StaticInterface</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            };</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">template</span>&lt;<span class="keyword">class</span>, <span class="keyword">class</span>...&gt; <span class="keyword">class </span>M, <span class="keyword">class </span>T, <span class="keyword">class </span>... Args&gt;</div><div class="line"><a name="l00035"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php">   35</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_utility_1_1_static_interface.php">StaticInterface</a>&lt;M&lt;T, Args...&gt;&gt; {</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php#a1cc03327db3207c7773f6891592e1ff1">   40</a></span>&#160;<span class="comment"></span>                    T&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php#a1cc03327db3207c7773f6891592e1ff1">impl</a>() {</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                        <span class="keywordflow">return</span> static_cast &lt;T&amp;&gt; (*this);</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    }</div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php#add3310980a57c3310ae92ff51e138133">   46</a></span>&#160;                    T <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php#add3310980a57c3310ae92ff51e138133">impl</a>()<span class="keyword"> const </span>{</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                        <span class="keywordflow">return</span> static_cast &lt;T <span class="keyword">const</span>&amp;&gt; (*this);</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                    }</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;            };</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        }</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4_php_add3310980a57c3310ae92ff51e138133"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php#add3310980a57c3310ae92ff51e138133">NRE::Utility::StaticInterface&lt; M&lt; T, Args... &gt; &gt;::impl</a></div><div class="ttdeci">T const &amp; impl() const </div><div class="ttdef"><b>Definition:</b> NRE_StaticInterface.hpp:46</div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4_php_a1cc03327db3207c7773f6891592e1ff1"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php#a1cc03327db3207c7773f6891592e1ff1">NRE::Utility::StaticInterface&lt; M&lt; T, Args... &gt; &gt;::impl</a></div><div class="ttdeci">T &amp; impl()</div><div class="ttdef"><b>Definition:</b> NRE_StaticInterface.hpp:40</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_utility_1_1_static_interface_php"><div class="ttname"><a href="class_n_r_e_1_1_utility_1_1_static_interface.php">NRE::Utility::StaticInterface</a></div><div class="ttdoc">Describe an object using CRTP to create static interface (static polymorphism) </div><div class="ttdef"><b>Definition:</b> NRE_StaticInterface.hpp:28</div></div>
<div class="ttc" id="namespace_utility_php"><div class="ttname"><a href="namespace_utility.php">Utility</a></div><div class="ttdoc">Utility&amp;#39;s API. </div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
