<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Class List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class List</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">Here are the classes, structs, unions and interfaces with brief descriptions:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span><span onclick="javascript:toggleLevel(5);">5</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><a class="el" href="namespace_n_r_e.php" target="_self">NRE</a></td><td class="desc">The NearlyRealEngine's global namespace </td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_0_" class="arrow" onclick="toggleFolder('0_0_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><b>Exception</b></td><td class="desc"></td></tr>
<tr id="row_0_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_i_exception.php" target="_self">IException</a></td><td class="desc">An interface for exception </td></tr>
<tr id="row_0_1_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_1_" class="arrow" onclick="toggleFolder('0_1_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><b>Utility</b></td><td class="desc"></td></tr>
<tr id="row_0_1_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_1_0_" class="arrow" onclick="toggleFolder('0_1_0_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><b>Detail</b></td><td class="desc"></td></tr>
<tr id="row_0_1_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_0_0_" class="arrow" onclick="toggleFolder('0_1_0_0_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><b>ForwardListInner</b></td><td class="desc"></td></tr>
<tr id="row_0_1_0_0_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php" target="_self">ForwardIterator</a></td><td class="desc">Internal iterator for forward list </td></tr>
<tr id="row_0_1_0_0_1_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node.php" target="_self">Node</a></td><td class="desc">Internal data structure to store forward list node </td></tr>
<tr id="row_0_1_0_0_2_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php" target="_self">NodeBase</a></td><td class="desc">Internal data structure to store forward list node </td></tr>
<tr id="row_0_1_0_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_1_0_1_" class="arrow" onclick="toggleFolder('0_1_0_1_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><b>HashTableInner</b></td><td class="desc"></td></tr>
<tr id="row_0_1_0_1_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php" target="_self">BucketEntry</a></td><td class="desc">A bucket entry used as the hash table elements </td></tr>
<tr id="row_0_1_0_1_1_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php" target="_self">BucketEntryHash</a></td><td class="desc">Used to store the key hash, or not depending on the template value </td></tr>
<tr id="row_0_1_0_1_2_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash_3_01true_01_4.php" target="_self">BucketEntryHash&lt; true &gt;</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_1_3_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php" target="_self">ForwardIterator</a></td><td class="desc">Hash table forward iterator </td></tr>
<tr id="row_0_1_0_1_4_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php" target="_self">LocalForwardIterator</a></td><td class="desc">Hash table local forward iterator </td></tr>
<tr id="row_0_1_0_2_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php" target="_self">ForwardList</a></td><td class="desc">A simple linked list </td></tr>
<tr id="row_0_1_0_3_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php" target="_self">HashTable</a></td><td class="desc">Based on TSL Robin Hash, An hashtable used in map and set, an associative container using linear probing, robin hood and shift back optimisation </td></tr>
<tr id="row_0_1_0_4_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php" target="_self">UnorderedMap</a></td><td class="desc">An unordered map, associative unordered container </td></tr>
<tr id="row_0_1_0_5_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php" target="_self">Vector</a></td><td class="desc">A dynamic array, guarantee to be in contiguous memory </td></tr>
<tr id="row_0_1_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php" target="_self">Array</a></td><td class="desc">A fixed size array </td></tr>
<tr id="row_0_1_2_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php" target="_self">BasicString</a></td><td class="desc">A basic template string, with dynamic size, guarantee to be in contiguous memory </td></tr>
<tr id="row_0_1_3_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_bidirectional_iterator.php" target="_self">BidirectionalIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_bidirectional_iterator.php" title="Used in IteratorTraits to detect BidirectionalIterator category. ">BidirectionalIterator</a> category </td></tr>
<tr id="row_0_1_4_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_forward_iterator.php" target="_self">ForwardIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_forward_iterator.php" title="Used in IteratorTraits to detect ForwardIterator category. ">ForwardIterator</a> category </td></tr>
<tr id="row_0_1_5_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_in_out_bidirectional_iterator.php" target="_self">InOutBidirectionalIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_bidirectional_iterator.php" title="Used in IteratorTraits to detect BidirectionalIterator category. ">BidirectionalIterator</a> category allowing Output operation </td></tr>
<tr id="row_0_1_6_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_in_out_forward_iterator.php" target="_self">InOutForwardIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_forward_iterator.php" title="Used in IteratorTraits to detect ForwardIterator category. ">ForwardIterator</a> category allowing Output operation </td></tr>
<tr id="row_0_1_7_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_in_out_random_access_iterator.php" target="_self">InOutRandomAccessIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_random_access_iterator.php" title="Used in IteratorTraits to detect RandomAccessIterator category. ">RandomAccessIterator</a> category allowing Output operation </td></tr>
<tr id="row_0_1_8_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_input_iterator.php" target="_self">InputIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_input_iterator.php" title="Used in IteratorTraits to detect InputIterator category. ">InputIterator</a> category </td></tr>
<tr id="row_0_1_9_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_bidirectional_iterator.php" target="_self">IsBidirectionalIterator</a></td><td class="desc">Detect if the given template paramter is an <a class="el" href="struct_n_r_e_1_1_utility_1_1_bidirectional_iterator.php" title="Used in IteratorTraits to detect BidirectionalIterator category. ">BidirectionalIterator</a> </td></tr>
<tr id="row_0_1_10_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_input_iterator.php" target="_self">IsInputIterator</a></td><td class="desc">Detect if the given template paramter is an <a class="el" href="struct_n_r_e_1_1_utility_1_1_input_iterator.php" title="Used in IteratorTraits to detect InputIterator category. ">InputIterator</a> </td></tr>
<tr id="row_0_1_11_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_iterator.php" target="_self">IsIterator</a></td><td class="desc">Detect if the given template paramter is either an <a class="el" href="struct_n_r_e_1_1_utility_1_1_input_iterator.php" title="Used in IteratorTraits to detect InputIterator category. ">InputIterator</a> or an <a class="el" href="struct_n_r_e_1_1_utility_1_1_output_iterator.php" title="Used in IteratorTraits to detect OutputIterator category. ">OutputIterator</a> or directly iterable pointer </td></tr>
<tr id="row_0_1_12_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_iterator_3_01const_01_t_01_5_01_4.php" target="_self">IsIterator&lt; const T * &gt;</a></td><td class="desc"></td></tr>
<tr id="row_0_1_13_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_iterator_3_01_t_01_5_01_4.php" target="_self">IsIterator&lt; T * &gt;</a></td><td class="desc"></td></tr>
<tr id="row_0_1_14_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_output_iterator.php" target="_self">IsOutputIterator</a></td><td class="desc">Detect if the given template paramter is an <a class="el" href="struct_n_r_e_1_1_utility_1_1_output_iterator.php" title="Used in IteratorTraits to detect OutputIterator category. ">OutputIterator</a> </td></tr>
<tr id="row_0_1_15_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_is_random_access_iterator.php" target="_self">IsRandomAccessIterator</a></td><td class="desc">Detect if the given template paramter is an <a class="el" href="struct_n_r_e_1_1_utility_1_1_random_access_iterator.php" title="Used in IteratorTraits to detect RandomAccessIterator category. ">RandomAccessIterator</a> </td></tr>
<tr id="row_0_1_16_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" target="_self">IteratorTraits</a></td><td class="desc">Describe an iterator object </td></tr>
<tr id="row_0_1_17_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits_3_01_it_3_01_args_8_8_8_01_4_00_01_t_00_01_category_01_4.php" target="_self">IteratorTraits&lt; It&lt; Args... &gt;, T, Category &gt;</a></td><td class="desc"></td></tr>
<tr id="row_0_1_18_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php" target="_self">Observable</a></td><td class="desc">Describe an observable object, coupled with observer </td></tr>
<tr id="row_0_1_19_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php" target="_self">Observer</a></td><td class="desc">Describe an observer object attached to an <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php" title="Describe an observable object, coupled with observer. ">Observable</a> </td></tr>
<tr id="row_0_1_20_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_output_iterator.php" target="_self">OutputIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_output_iterator.php" title="Used in IteratorTraits to detect OutputIterator category. ">OutputIterator</a> category </td></tr>
<tr id="row_0_1_21_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_pair.php" target="_self">Pair</a></td><td class="desc">A basic template pair </td></tr>
<tr id="row_0_1_22_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="struct_n_r_e_1_1_utility_1_1_random_access_iterator.php" target="_self">RandomAccessIterator</a></td><td class="desc">Used in <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" title="Describe an iterator object. ">IteratorTraits</a> to detect <a class="el" href="struct_n_r_e_1_1_utility_1_1_random_access_iterator.php" title="Used in IteratorTraits to detect RandomAccessIterator category. ">RandomAccessIterator</a> category </td></tr>
<tr id="row_0_1_23_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_singleton.php" target="_self">Singleton</a></td><td class="desc">Describe a singleton object </td></tr>
<tr id="row_0_1_24_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php" target="_self">Stack</a></td><td class="desc">A stack adapter wrapping a container class </td></tr>
<tr id="row_0_1_25_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php" target="_self">StaticInterface</a></td><td class="desc">Describe an object using CRTP to create static interface (static polymorphism) </td></tr>
<tr id="row_0_1_26_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface_3_01_m_3_01_t_00_01_args_8_8_8_01_4_01_4.php" target="_self">StaticInterface&lt; M&lt; T, Args... &gt; &gt;</a></td><td class="desc"></td></tr>
<tr id="row_0_1_27_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php" target="_self">StaticVector</a></td><td class="desc">A static vector, with a fixed size capacity on the stack but vector behavior </td></tr>
<tr id="row_0_1_28_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_stringable.php" target="_self">Stringable</a></td><td class="desc">Describe an stringable object </td></tr>
<tr id="row_0_1_29_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_utility_1_1_uncopyable.php" target="_self">Uncopyable</a></td><td class="desc">Describe an un-copyable object </td></tr>
<tr id="row_1_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_1_" class="arrow" onclick="toggleFolder('1_')">&#9660;</span><span class="icona"><span class="icon">N</span></span><a class="el" href="namespacestd.php" target="_self">std</a></td><td class="desc">The stl standard namespace </td></tr>
<tr id="row_1_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="classstd_1_1hash_3_01_n_r_e_1_1_utility_1_1_string_01_4.php" target="_self">hash&lt; NRE::Utility::String &gt;</a></td><td class="desc"></td></tr>
<tr id="row_2_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="classhash.php" target="_self">hash</a></td><td class="desc">Manage hashing for specialized version </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
