<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">Stack</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Utility::Stack&lt; T, Container &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a7056eedccf0985dfc6b83811373765ae">emplace</a>(Args &amp;&amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a41619ddba878602b48c277facb3e2e11">getSize</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#abd7056182ae176012d9f55cedf427813">getTop</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a284ae53875efd2089e1e7ae3cdc32a5f">getTop</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php#a72fd5f7816f2a8309328186e1bf2b2f5">impl</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php">NRE::Utility::StaticInterface&lt; T, M &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php#a1fcc521ea437ea9edceae7f0c03ab6b1">impl</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php">NRE::Utility::StaticInterface&lt; T, M &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#ad2c84dfbe7f88a6c0350b400b593e251">isEmpty</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#ac3cd88146c5182ab3e876440c329ab31">operator!=</a>(Stack const &amp;s) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#aa0591770d9d6ffd0b3d20b91b7632030">operator=</a>(Stack const &amp;s)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a09de02457ac5adbf31da634b357ab9ae">operator=</a>(Stack &amp;&amp;s)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a39f4b130a39d707e1f26a6e1ae7911ea">operator==</a>(Stack const &amp;s) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a27f8d9c497e05251326a49655bd9da48">pop</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a4cf97be0bf934c70ead58c5fef7853aa">push</a>(T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#acc50e85f466cc273d80552bd03b1a2db">push</a>(T &amp;&amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a0fb9f26708174bd16ad33be23fa79b0b">Stack</a>(Container &amp;&amp;container=Container())</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#aa2aa3d8c8351d2b329e15771c9ed9162">Stack</a>(Container const &amp;container)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a5a37323d578364e4a5848d0a83e43e76">Stack</a>(Stack const &amp;s)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a814a2b791dbd4555d658e2686e51d41f">Stack</a>(Stack &amp;&amp;s)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#aa7846ea11319d74378c03278fa5ac7b0">swap</a>(Stack &amp;s)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a9259e7119a6d5a7c50770431379098b1">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#abde8678c62784d73239a488e6a16f8d3">~Stack</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php">NRE::Utility::Stack&lt; T, Container &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
