<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">Vector</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Utility::Vector&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ad26076d90066a1a8179e08a7cc7a8bf9">assign</a>(std::size_t count, T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a98b87cbf6835d6c369fdd28acebf7bcc">assign</a>(InputIterator begin, InputIterator end)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a7aa353d783fef64406568550d4a883d1">begin</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a6bd2d0b71d8e8b93861c4caafc9fd041">begin</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a1235e24f29b8c798448f7212223ac2db">cbegin</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a3e05dac568e481aa3dc99bcb2fa81bc5">cend</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#adbf7f3450844b9fea8610732c2912d8e">clear</a>() noexcept</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#adbf7f3450844b9fea8610732c2912d8e">clear</a>() noexcept</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a00fbf24e911c0a9ccee4a3b0eac8e5b1">ConstIterator</a> typedef</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>ConstReverseIterator</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#af1df2723bdc74b4ffab679a237ae2ae0">crbegin</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a02fb5d3837c5db11e7858f624acfdd5f">crend</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ab6ee01cb2c95fa62f6dab6cbdb7e5c95">emplace</a>(ConstIterator start, Args &amp;&amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a66855834bd04ef8d1e535909975b77e2">emplaceBack</a>(Args &amp;&amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a99c26a269e5bc0d86c3d2e048892354b">end</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aa7090789237db80716032b978ad6925d">end</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aace4ba5a783ddb11a1b39cf0b7ea92ff">erase</a>(ConstIterator pos)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ac632436e31cea20a8b5101c7539b9401">erase</a>(ConstIterator begin, ConstIterator end)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#acf66396d0b55328ebc94c784a0df1202">get</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a9c8c21b9db893e000a1266613745969a">get</a>(std::size_t index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a6b86482f38d63cbffe6c0fb9b932cf76">getCapacity</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a2ae8d5da9a73f3528d1b65295b237c63">getData</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a19f058f1553671eaf31c1c033fa26954">getData</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a873741553e4a855885aa842f248c9f11">getFront</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a156b7c07b9608e4fb4817b478ab263db">getFront</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aca0d6f2c796a4a7ef2a54edf4a69324d">getLast</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aa0cc91b6cfc7f3a6fa5fd4d49252c918">getLast</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a0a98316cb06dd62423ad1c184e84d838">getMaxSize</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a8c120aaf679f48aa5bb4f7ee51ea9ff6">getSize</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php#a72fd5f7816f2a8309328186e1bf2b2f5">impl</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php">NRE::Utility::StaticInterface&lt; T, M &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php#a1fcc521ea437ea9edceae7f0c03ab6b1">impl</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_static_interface.php">NRE::Utility::StaticInterface&lt; T, M &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a95239a3a4d64dcded470a0e7a68326a3">insert</a>(ConstIterator start, T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a782e5af524b191b0269ea34f7538a89d">insert</a>(ConstIterator start, std::size_t count, T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#abd2e9405d07a56c3071bc6b9e7b8c012">insert</a>(ConstIterator start, InputIterator begin, InputIterator end)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a35381933cdb7b1bc72a689adc542d2eb">insert</a>(ConstIterator start, std::initializer_list&lt; T &gt; list)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ab053cb0a3701212b7e0a352a4d410c04">isEmpty</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a4f62eb0eba61b38e5f6b03c60ea6a49c">Iterator</a> typedef</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#adc1b419631e45a8e8a8cdafe02be6129">operator!=</a>(Vector const &amp;vec) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a0d79e58c0fa7ea52628a3b84b54a1c6f">operator=</a>(Vector const &amp;vec)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a1e6a1628e4c81bb6203fdee57f8d2eba">operator=</a>(Vector &amp;&amp;vec)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aff21ca4b619758e7d5f816113750d5dd">operator==</a>(Vector const &amp;vec) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aff21ca4b619758e7d5f816113750d5dd">operator==</a>(Vector const &amp;vec) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a6fabf24c5fb7d29cce7217a2d52f832f">operator[]</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a37835b4a75e13ed9b57194e7fe5a82c6">operator[]</a>(std::size_t index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a3d808b6e7fedafc95b472c3dda5af3f0">popBack</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a3d808b6e7fedafc95b472c3dda5af3f0">popBack</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a1275882662e370b622c78880ed57a703">pushBack</a>(T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a66c4300aaa3ddf9f2f802a4ac0184b56">pushBack</a>(T &amp;&amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a5ed9cfc1f219ef3670d02dbb938da41d">rbegin</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a41f5e611ca8bd827e3c1e92a60edc538">rbegin</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a5455bed3ad1618600685de6ca73e8f2d">rend</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a2e6476aee682496635d945f90a5a31f8">rend</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a53b14e9f414f1304e2e3fb1c39bb7086">reserve</a>(std::size_t size)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#af414d545204d0288d12293382c5c091e">resize</a>(std::size_t count)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ad4d461cc13fa0fd2c7e1d9ad720b7dc9">resize</a>(std::size_t count, T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a52eee3309a729b97a0e9fd9e76a07fae">ReverseIterator</a> typedef</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#abfda77f44caf07a116636de6daebf336">shrinkToFit</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a7178023d23d25c5bf762c1851044042f">swap</a>(Vector &amp;vec)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ae06ea911c6026374457bfc4ba19d8d57">toString</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ad4013a6eedf95e4f7ba991da26c9bc5c">Vector</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a5bc29c9c9d6a40ebc115809f47a04450">Vector</a>(std::size_t count, T const &amp;value)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a98ccb1caf205e8d2d1a020312178e391">Vector</a>(std::size_t count)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#abd6844c8f8c1eb9bb166c5e8835dffa8">Vector</a>(InputIterator begin, InputIterator end)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#a8aeb3526769c90067a39e4bb55a9522e">Vector</a>(std::initializer_list&lt; T &gt; init)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aaf301a43eaedc067e0221ac4800735f9">Vector</a>(Vector const &amp;vec)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#aed6e950035f2718400f96c89e4aa9761">Vector</a>(Vector &amp;&amp;vec)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php#ab29b80e7a67b9530485c6771465bce28">~Vector</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_vector.php">NRE::Utility::Vector&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
