<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><b>Detail</b></li><li class="navelem"><b>HashTableInner</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Hash table local forward iterator.  
 <a href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.png" usemap="#NRE::Utility::Detail::HashTableInner::LocalForwardIterator_3C_20T_2C_20Category_2C_20Bucket_20_3E_map" alt=""/>
  <map id="NRE::Utility::Detail::HashTableInner::LocalForwardIterator_3C_20T_2C_20Category_2C_20Bucket_20_3E_map" name="NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" alt="NRE::Utility::IteratorBase&lt; ForwardIterator&lt; T, Category, Bucket &gt;, T, Category &gt;" shape="rect" coords="0,0,478,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a2825089356bfd85b5d7d7db054194593"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a2825089356bfd85b5d7d7db054194593">Traits</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php">IteratorBase</a>&lt; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt;, T, Category &gt;</td></tr>
<tr class="separator:a2825089356bfd85b5d7d7db054194593"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3658f20355955264dc2a08d24cae3ee"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ad3658f20355955264dc2a08d24cae3ee">ValueType</a> = typename Traits::ValueType</td></tr>
<tr class="separator:ad3658f20355955264dc2a08d24cae3ee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28ce846fce3ff622ea4856c1dcd1c557"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a28ce846fce3ff622ea4856c1dcd1c557">Pointer</a> = typename Traits::Pointer</td></tr>
<tr class="separator:a28ce846fce3ff622ea4856c1dcd1c557"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac36dfe5ac0e29d2315a18676aba3b132"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">Reference</a> = typename Traits::Reference</td></tr>
<tr class="separator:ac36dfe5ac0e29d2315a18676aba3b132"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa460150794841790f5691bf510a8e98c"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#aa460150794841790f5691bf510a8e98c">DifferenceType</a> = typename Traits::DifferenceType</td></tr>
<tr class="separator:aa460150794841790f5691bf510a8e98c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a58370f850743434282b30431983841d5"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a58370f850743434282b30431983841d5">value_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ad3658f20355955264dc2a08d24cae3ee">ValueType</a></td></tr>
<tr class="separator:a58370f850743434282b30431983841d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b58150a0b84305ff72cee6ce1295bf3"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a3b58150a0b84305ff72cee6ce1295bf3">pointer</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a28ce846fce3ff622ea4856c1dcd1c557">Pointer</a></td></tr>
<tr class="separator:a3b58150a0b84305ff72cee6ce1295bf3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af90a7a16e16cfd3cc79a0db9a145ee83"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#af90a7a16e16cfd3cc79a0db9a145ee83">reference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">Reference</a></td></tr>
<tr class="separator:af90a7a16e16cfd3cc79a0db9a145ee83"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a33b2a58489245bac32a98b6da1004fee"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a33b2a58489245bac32a98b6da1004fee">difference_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#aa460150794841790f5691bf510a8e98c">DifferenceType</a></td></tr>
<tr class="separator:a33b2a58489245bac32a98b6da1004fee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0a7c1e256519afd86da92c0b31132af6"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a0a7c1e256519afd86da92c0b31132af6">iterator_category</a> = typename Traits::iterator_category</td></tr>
<tr class="separator:a0a7c1e256519afd86da92c0b31132af6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ab0dff95693e1987dc643ecfc94b73687"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ab0dff95693e1987dc643ecfc94b73687">LocalForwardIterator</a> ()=default</td></tr>
<tr class="separator:ab0dff95693e1987dc643ecfc94b73687"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4fbb4e0d54a849219a879a1bdc81e5e0"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a4fbb4e0d54a849219a879a1bdc81e5e0">LocalForwardIterator</a> (Bucket *bucket)</td></tr>
<tr class="separator:a4fbb4e0d54a849219a879a1bdc81e5e0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae7583b8bf3c0a1aae03d09bed254b27f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ae7583b8bf3c0a1aae03d09bed254b27f">LocalForwardIterator</a> (const Bucket *bucket)</td></tr>
<tr class="separator:ae7583b8bf3c0a1aae03d09bed254b27f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4e951f8ea5a075b5a5613c4bcde2f0e3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a4e951f8ea5a075b5a5613c4bcde2f0e3">LocalForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a4e951f8ea5a075b5a5613c4bcde2f0e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a164beb7d996d76122c7dcbdc69c0a286"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a164beb7d996d76122c7dcbdc69c0a286">LocalForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> &amp;&amp;it)=default</td></tr>
<tr class="separator:a164beb7d996d76122c7dcbdc69c0a286"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e899633c233597428388473f9d8e856"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a0e899633c233597428388473f9d8e856">~LocalForwardIterator</a> ()=default</td></tr>
<tr class="separator:a0e899633c233597428388473f9d8e856"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a71e2631757c857211857c33b5fdddd46"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a71e2631757c857211857c33b5fdddd46">dereference</a> () const </td></tr>
<tr class="separator:a71e2631757c857211857c33b5fdddd46"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f42b5feb12211e0b420379adbb41120"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a3f42b5feb12211e0b420379adbb41120">increment</a> ()</td></tr>
<tr class="separator:a3f42b5feb12211e0b420379adbb41120"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a245980557bc3105393f16a1f33904338"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a245980557bc3105393f16a1f33904338">equal</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> const &amp;it) const </td></tr>
<tr class="separator:a245980557bc3105393f16a1f33904338"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa39af582014a3a0fce0be6c87c8ec095"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#aa39af582014a3a0fce0be6c87c8ec095">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:aa39af582014a3a0fce0be6c87c8ec095"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad2c73b1fa70abaf7689a9d4c6623de5a"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ad2c73b1fa70abaf7689a9d4c6623de5a">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> &amp;&amp;it)=default</td></tr>
<tr class="separator:ad2c73b1fa70abaf7689a9d4c6623de5a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, class Category, class Bucket&gt;<br />
class NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt;</h3>

<p>Hash table local forward iterator. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a33b2a58489245bac32a98b6da1004fee"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a33b2a58489245bac32a98b6da1004fee">difference_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#aa460150794841790f5691bf510a8e98c">DifferenceType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="aa460150794841790f5691bf510a8e98c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#aa460150794841790f5691bf510a8e98c">DifferenceType</a> =  typename Traits::DifferenceType</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterator difference type </p>

</div>
</div>
<a class="anchor" id="a0a7c1e256519afd86da92c0b31132af6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a0a7c1e256519afd86da92c0b31132af6">iterator_category</a> =  typename Traits::iterator_category</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a28ce846fce3ff622ea4856c1dcd1c557"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a28ce846fce3ff622ea4856c1dcd1c557">Pointer</a> =  typename Traits::Pointer</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The pointer on iterated object </p>

</div>
</div>
<a class="anchor" id="a3b58150a0b84305ff72cee6ce1295bf3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a3b58150a0b84305ff72cee6ce1295bf3">pointer</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a28ce846fce3ff622ea4856c1dcd1c557">Pointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="ac36dfe5ac0e29d2315a18676aba3b132"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">Reference</a> =  typename Traits::Reference</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The reference on iterated object </p>

</div>
</div>
<a class="anchor" id="af90a7a16e16cfd3cc79a0db9a145ee83"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#af90a7a16e16cfd3cc79a0db9a145ee83">reference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">Reference</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a2825089356bfd85b5d7d7db054194593"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a2825089356bfd85b5d7d7db054194593">Traits</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php">IteratorBase</a>&lt;<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt;T, Category, Bucket&gt;, T, Category&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inherited iterator traits </p>

</div>
</div>
<a class="anchor" id="a58370f850743434282b30431983841d5"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a58370f850743434282b30431983841d5">value_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ad3658f20355955264dc2a08d24cae3ee">ValueType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="ad3658f20355955264dc2a08d24cae3ee"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ad3658f20355955264dc2a08d24cae3ee">ValueType</a> =  typename Traits::ValueType</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterated object </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ab0dff95693e1987dc643ecfc94b73687"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor with nullptr node </p>

</div>
</div>
<a class="anchor" id="a4fbb4e0d54a849219a879a1bdc81e5e0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">Bucket *&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the iterator bucket </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae7583b8bf3c0a1aae03d09bed254b27f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">const Bucket *&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the iterator bucket </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a4e951f8ea5a075b5a5613c4bcde2f0e3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&lt; T, Category, Bucket &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a164beb7d996d76122c7dcbdc69c0a286"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&lt; T, Category, Bucket &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a0e899633c233597428388473f9d8e856"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php" title="Hash table local forward iterator. ">LocalForwardIterator</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a71e2631757c857211857c33b5fdddd46"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::dereference </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a reference on the iterated data </dd></dl>

</div>
</div>
<a class="anchor" id="a245980557bc3105393f16a1f33904338"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::equal </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&lt; T, Category, Bucket &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if the given iterator point to the same position </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the other iterator </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a3f42b5feb12211e0b420379adbb41120"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::increment </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Increment the iterator position by one </p>

</div>
</div>
<a class="anchor" id="aa39af582014a3a0fce0be6c87c8ec095"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&lt; T, Category, Bucket &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ad2c73b1fa70abaf7689a9d4c6623de5a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">NRE::Utility::Detail::HashTableInner::LocalForwardIterator</a>&lt; T, Category, Bucket &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php">LocalForwardIterator</a>&lt; T, Category, Bucket &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Detail/HashTable/<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
