<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><b>Detail</b></li><li class="navelem"><b>HashTableInner</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Hash table forward iterator.  
 <a href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.png" usemap="#NRE::Utility::Detail::HashTableInner::ForwardIterator_3C_20T_2C_20Category_2C_20Bucket_20_3E_map" alt=""/>
  <map id="NRE::Utility::Detail::HashTableInner::ForwardIterator_3C_20T_2C_20Category_2C_20Bucket_20_3E_map" name="NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" alt="NRE::Utility::IteratorBase&lt; ForwardIterator&lt; T, Category, Bucket &gt;, T, Category &gt;" shape="rect" coords="0,0,478,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:ac8bfbd9d1f57d41c8639eabc7aa0116f"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ac8bfbd9d1f57d41c8639eabc7aa0116f">Traits</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php">IteratorBase</a>&lt; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt;, T, Category &gt;</td></tr>
<tr class="separator:ac8bfbd9d1f57d41c8639eabc7aa0116f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac10c16cbd77db61e0c0ba0faee471e4e"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ac10c16cbd77db61e0c0ba0faee471e4e">ValueType</a> = typename Traits::ValueType</td></tr>
<tr class="separator:ac10c16cbd77db61e0c0ba0faee471e4e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7c6d57464fbe894b22ee5577450616c9"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a7c6d57464fbe894b22ee5577450616c9">Pointer</a> = typename Traits::Pointer</td></tr>
<tr class="separator:a7c6d57464fbe894b22ee5577450616c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa727a09a1eca99861990ff60fd628f94"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">Reference</a> = typename Traits::Reference</td></tr>
<tr class="separator:aa727a09a1eca99861990ff60fd628f94"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adedb8a350a2c084f9b8b1c5ed29b4b35"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#adedb8a350a2c084f9b8b1c5ed29b4b35">DifferenceType</a> = typename Traits::DifferenceType</td></tr>
<tr class="separator:adedb8a350a2c084f9b8b1c5ed29b4b35"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a23a518e5e85181ae9ec897fcbe4f9b6d"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a23a518e5e85181ae9ec897fcbe4f9b6d">value_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ac10c16cbd77db61e0c0ba0faee471e4e">ValueType</a></td></tr>
<tr class="separator:a23a518e5e85181ae9ec897fcbe4f9b6d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a90423bd688acefee4bc0fb1f40c442a9"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a90423bd688acefee4bc0fb1f40c442a9">pointer</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a7c6d57464fbe894b22ee5577450616c9">Pointer</a></td></tr>
<tr class="separator:a90423bd688acefee4bc0fb1f40c442a9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acd808453bbe076074bca6ba4a2d9a0c4"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#acd808453bbe076074bca6ba4a2d9a0c4">reference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">Reference</a></td></tr>
<tr class="separator:acd808453bbe076074bca6ba4a2d9a0c4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0816b4bc1352bca9a1dbd3a3f976de86"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a0816b4bc1352bca9a1dbd3a3f976de86">difference_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#adedb8a350a2c084f9b8b1c5ed29b4b35">DifferenceType</a></td></tr>
<tr class="separator:a0816b4bc1352bca9a1dbd3a3f976de86"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afc7a25767ad5e09fe9f14785f7f89a6c"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#afc7a25767ad5e09fe9f14785f7f89a6c">iterator_category</a> = typename Traits::iterator_category</td></tr>
<tr class="separator:afc7a25767ad5e09fe9f14785f7f89a6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a99546f8a7afdb1eb2eac5851301fc2db"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a99546f8a7afdb1eb2eac5851301fc2db">ForwardIterator</a> ()=default</td></tr>
<tr class="separator:a99546f8a7afdb1eb2eac5851301fc2db"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a957ae32726c273b4b6a7f0ce1b11b0ec"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a957ae32726c273b4b6a7f0ce1b11b0ec">ForwardIterator</a> (Bucket *bucket)</td></tr>
<tr class="separator:a957ae32726c273b4b6a7f0ce1b11b0ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad4cc956ec8a6ac2dac478d934e5f5d13"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ad4cc956ec8a6ac2dac478d934e5f5d13">ForwardIterator</a> (const Bucket *bucket)</td></tr>
<tr class="separator:ad4cc956ec8a6ac2dac478d934e5f5d13"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a23175bc8a2c8feff23b6679b00f1f60a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a23175bc8a2c8feff23b6679b00f1f60a">ForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a23175bc8a2c8feff23b6679b00f1f60a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5f04a272be22e1efab3c0513005c8a40"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a5f04a272be22e1efab3c0513005c8a40">ForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&amp;it)=default</td></tr>
<tr class="separator:a5f04a272be22e1efab3c0513005c8a40"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5cf2f0aa3344066ba4c8d37f372ab08"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#af5cf2f0aa3344066ba4c8d37f372ab08">~ForwardIterator</a> ()=default</td></tr>
<tr class="separator:af5cf2f0aa3344066ba4c8d37f372ab08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61b660de80c2fde95b0fe7ebfbf61290"><td class="memItemLeft" align="right" valign="top">Bucket *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a61b660de80c2fde95b0fe7ebfbf61290">getCurrent</a> ()</td></tr>
<tr class="separator:a61b660de80c2fde95b0fe7ebfbf61290"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a72512f133d709c8f6547e9034ebac2bf"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a72512f133d709c8f6547e9034ebac2bf">dereference</a> () const </td></tr>
<tr class="separator:a72512f133d709c8f6547e9034ebac2bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af67d7b3aa5d82609e162f63c2ae66366"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#af67d7b3aa5d82609e162f63c2ae66366">increment</a> ()</td></tr>
<tr class="separator:af67d7b3aa5d82609e162f63c2ae66366"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5315f9dec5de449954919e12ec89b861"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a5315f9dec5de449954919e12ec89b861">equal</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it) const </td></tr>
<tr class="separator:a5315f9dec5de449954919e12ec89b861"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a842b3f70337d369bc26f057c3647be46"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a842b3f70337d369bc26f057c3647be46">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a842b3f70337d369bc26f057c3647be46"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a69f29a8422c29c28cf8e5af5ef9b93e7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a69f29a8422c29c28cf8e5af5ef9b93e7">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&amp;it)=default</td></tr>
<tr class="separator:a69f29a8422c29c28cf8e5af5ef9b93e7"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, class Category, class Bucket&gt;<br />
class NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt;</h3>

<p>Hash table forward iterator. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a0816b4bc1352bca9a1dbd3a3f976de86"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a0816b4bc1352bca9a1dbd3a3f976de86">difference_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#adedb8a350a2c084f9b8b1c5ed29b4b35">DifferenceType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="adedb8a350a2c084f9b8b1c5ed29b4b35"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#adedb8a350a2c084f9b8b1c5ed29b4b35">DifferenceType</a> =  typename Traits::DifferenceType</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterator difference type </p>

</div>
</div>
<a class="anchor" id="afc7a25767ad5e09fe9f14785f7f89a6c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#afc7a25767ad5e09fe9f14785f7f89a6c">iterator_category</a> =  typename Traits::iterator_category</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a7c6d57464fbe894b22ee5577450616c9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a7c6d57464fbe894b22ee5577450616c9">Pointer</a> =  typename Traits::Pointer</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The pointer on iterated object </p>

</div>
</div>
<a class="anchor" id="a90423bd688acefee4bc0fb1f40c442a9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a90423bd688acefee4bc0fb1f40c442a9">pointer</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a7c6d57464fbe894b22ee5577450616c9">Pointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="aa727a09a1eca99861990ff60fd628f94"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">Reference</a> =  typename Traits::Reference</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The reference on iterated object </p>

</div>
</div>
<a class="anchor" id="acd808453bbe076074bca6ba4a2d9a0c4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#acd808453bbe076074bca6ba4a2d9a0c4">reference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">Reference</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="ac8bfbd9d1f57d41c8639eabc7aa0116f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ac8bfbd9d1f57d41c8639eabc7aa0116f">Traits</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php">IteratorBase</a>&lt;<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt;T, Category, Bucket&gt;, T, Category&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inherited iterator traits </p>

</div>
</div>
<a class="anchor" id="a23a518e5e85181ae9ec897fcbe4f9b6d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a23a518e5e85181ae9ec897fcbe4f9b6d">value_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ac10c16cbd77db61e0c0ba0faee471e4e">ValueType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="ac10c16cbd77db61e0c0ba0faee471e4e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#ac10c16cbd77db61e0c0ba0faee471e4e">ValueType</a> =  typename Traits::ValueType</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterated object </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a99546f8a7afdb1eb2eac5851301fc2db"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor with nullptr node </p>

</div>
</div>
<a class="anchor" id="a957ae32726c273b4b6a7f0ce1b11b0ec"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">Bucket *&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the iterator bucket </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad4cc956ec8a6ac2dac478d934e5f5d13"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">const Bucket *&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the iterator bucket </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a23175bc8a2c8feff23b6679b00f1f60a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a5f04a272be22e1efab3c0513005c8a40"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af5cf2f0aa3344066ba4c8d37f372ab08"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php" title="Hash table forward iterator. ">ForwardIterator</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a72512f133d709c8f6547e9034ebac2bf"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::dereference </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a reference on the iterated data </dd></dl>

</div>
</div>
<a class="anchor" id="a5315f9dec5de449954919e12ec89b861"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::equal </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if the given iterator point to the same position </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the other iterator </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a61b660de80c2fde95b0fe7ebfbf61290"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">Bucket* <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::getCurrent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the current bucket </dd></dl>

</div>
</div>
<a class="anchor" id="af67d7b3aa5d82609e162f63c2ae66366"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::increment </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Increment the iterator position by one </p>

</div>
</div>
<a class="anchor" id="a842b3f70337d369bc26f057c3647be46"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a69f29a8422c29c28cf8e5af5ef9b93e7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category , class Bucket &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">NRE::Utility::Detail::HashTableInner::ForwardIterator</a>&lt; T, Category, Bucket &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category, Bucket &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Detail/HashTable/<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
