<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a84fc56821cc153a9d0e7908ba3f729c6">BucketEntry</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a130a66ff82bfb2640d0b5574036ffdfb">BucketEntry</a>(bool state)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a4b796870d26f0547f61823803f7cc637">BucketEntry</a>(BucketEntry const &amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#ade0e9c2f08f57fc567433ada7ce770dc">BucketEntry</a>(BucketEntry &amp;&amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php#a6a0f44c490c0f828d1377a231d1166d4">bucketHashEquals</a>(std::size_t) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php">NRE::Utility::BucketEntryHash&lt; StoreHash &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a7b2ec6028e7b2d2bb1197b01a10e7556">clear</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>DistanceType</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a0fef8d48cbabdbc2ad0f8f1bfeccbf9a">EMPTY_BUCKET_DISTANCE</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a4c71f9d6079559245b4e76031cc717ec">getData</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a3c7706e4b1f93b61dc3cf22f64614e24">getData</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a6cd8a0f0faa075f231602ff5d62bf868">getDistanceToNext</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php#a649b8be8873d8550244a7656a98921e1">getTruncatedHash</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php">NRE::Utility::BucketEntryHash&lt; StoreHash &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a16a68a93ffc4a2df040db1987dfdcad2">isEmpty</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a8a561f866defb9fac335bb71961a6185">isLastBucket</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a95b0c1515d88bda0e43a228dbce95947">operator=</a>(BucketEntry const &amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a23e53df15b64945c974493162ea5f9d1">operator=</a>(BucketEntry &amp;&amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#ab62abac1cc7a97018d8ed074caf82315">setAsLastBucket</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a8a504da56b18c9c17e8fb5a232f1420b">setData</a>(DistanceType distance, TruncatedHash h, ValueType &amp;&amp;newData)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php#ac5fb7ad7eaffbd1b53fb77c49a8e2722">setHash</a>(TruncatedHash)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php">NRE::Utility::BucketEntryHash&lt; StoreHash &gt;</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">protected</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>Storage</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a8e545299519702f52cb4ecdc6d10318c">swapWithData</a>(DistanceType &amp;distance, TruncatedHash &amp;h, ValueType &amp;newData)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#adf920402af50f4a9c6c7606420de8f11">~BucketEntry</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
