<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><b>Detail</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a753c02f3e137b75e754754304f0f8e32">BucketEntry</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a5606e4b3d53eb79189edec14b1b651a4">BucketEntry</a>(bool state)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#ae904d88fd4387d5faf73f2f1040dece9">BucketEntry</a>(BucketEntry const &amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#abad3c49ed94e2d95f5b043d743225ca7">BucketEntry</a>(BucketEntry &amp;&amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php#a44bbda026b156df237763c94c030e5ae">bucketHashEquals</a>(std::size_t) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php">NRE::Utility::Detail::BucketEntryHash&lt; StoreHash &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a0052d0b421093bf5609cb13a0b9a19e9">clear</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>DistanceType</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#abbcb1b8b41205bc789a169b6683aecc6">EMPTY_BUCKET_DISTANCE</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a8e0613268c80ce19ab95e5ca966ba336">getData</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a6a0d7a5fdef78241e0d6126ba579e0ce">getData</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#aac0d7b65accda82311d88813896a8f15">getDistanceToNext</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php#ad1dc8a5312f8fc3a6189564eb8df152c">getTruncatedHash</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php">NRE::Utility::Detail::BucketEntryHash&lt; StoreHash &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a632987ad8cbbb52c78007c81cdd75b63">isEmpty</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a8ed2728946b71f255a445d78f6e57ed7">isLastBucket</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#ad947b55675d7af985c6aa4463e0d9ccf">operator=</a>(BucketEntry const &amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#afd0dac5051a38c9e39f6c18639f6a569">operator=</a>(BucketEntry &amp;&amp;bucket)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#acae75c13940ea2d5cfd5579d63253916">setAsLastBucket</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a697984f6cf8f34aa8670627bdab0bdab">setData</a>(DistanceType distance, TruncatedHash h, ValueType &amp;&amp;newData)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php#a7610dfcbf24281cb5eff7b7f08e95c76">setHash</a>(TruncatedHash)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php">NRE::Utility::Detail::BucketEntryHash&lt; StoreHash &gt;</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">protected</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>Storage</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a20f4afca0d279783b2bb98c07fd10178">swapWithData</a>(DistanceType &amp;distance, TruncatedHash &amp;h, ValueType &amp;newData)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a3ae7cc0e4b8a95a881eeee75aefd576b">~BucketEntry</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
