<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Array&lt; T, Size &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_array-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Array&lt; T, Size &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A fixed size array.  
 <a href="class_n_r_e_1_1_utility_1_1_array.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___array_8hpp_source.php">NRE_Array.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::Array&lt; T, Size &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_array.png" usemap="#NRE::Utility::Array_3C_20T_2C_20Size_20_3E_map" alt=""/>
  <map id="NRE::Utility::Array_3C_20T_2C_20Size_20_3E_map" name="NRE::Utility::Array&lt; T, Size &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_stringable.php" alt="NRE::Utility::Stringable&lt; Array&lt; T, Size &gt; &gt;" shape="rect" coords="0,56,362,80"/>
<area href="class_n_r_e_1_1_utility_1_1_static_interface.php" title="Describe an object using CRTP to create static interface (static polymorphism) " alt="NRE::Utility::StaticInterface&lt; T &gt;" shape="rect" coords="0,0,362,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a069bbb740098037643c0cb7712ef4b21"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> = T</td></tr>
<tr class="separator:a069bbb740098037643c0cb7712ef4b21"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a64b9ba4cfe847976b5a57605dde8f889"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> = std::size_t</td></tr>
<tr class="separator:a64b9ba4cfe847976b5a57605dde8f889"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a13503755383ed207497411583179745a"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a13503755383ed207497411583179745a">DifferenceType</a> = std::ptrdiff_t</td></tr>
<tr class="separator:a13503755383ed207497411583179745a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afa251a0df0a73baae67d39177cfaa90f"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> &amp;</td></tr>
<tr class="separator:afa251a0df0a73baae67d39177cfaa90f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a21b7b2c6b0d2cafb542c719c27f26418"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> const &amp;</td></tr>
<tr class="separator:a21b7b2c6b0d2cafb542c719c27f26418"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a473b201017e3513b1c05061cbd5223"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> *</td></tr>
<tr class="separator:a3a473b201017e3513b1c05061cbd5223"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2904cfdc42b306da7b6bbdebc948f3b0"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a> = const <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> *</td></tr>
<tr class="separator:a2904cfdc42b306da7b6bbdebc948f3b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1caa63883daa72f86cd6e912fbc62994"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a></td></tr>
<tr class="separator:a1caa63883daa72f86cd6e912fbc62994"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1d9c3cedc358c6fa37ead43cbbf39eec"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a></td></tr>
<tr class="separator:a1d9c3cedc358c6fa37ead43cbbf39eec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9f466da2cdfc8b3c07b9abf097d93acb"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a> = std::reverse_iterator&lt; <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a> &gt;</td></tr>
<tr class="separator:a9f466da2cdfc8b3c07b9abf097d93acb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a77341af327bf71857307ee0bcbb4a33a"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a> = std::reverse_iterator&lt; <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> &gt;</td></tr>
<tr class="separator:a77341af327bf71857307ee0bcbb4a33a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8de99b6b188fe6f33a7335e7754b441e"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8de99b6b188fe6f33a7335e7754b441e">value_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a></td></tr>
<tr class="separator:a8de99b6b188fe6f33a7335e7754b441e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a54963e0f1da053764235962bf9e5d000"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a54963e0f1da053764235962bf9e5d000">size_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a></td></tr>
<tr class="separator:a54963e0f1da053764235962bf9e5d000"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e9aa096d021bfb18e222f65dfea2869"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3e9aa096d021bfb18e222f65dfea2869">difference_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a13503755383ed207497411583179745a">DifferenceType</a></td></tr>
<tr class="separator:a3e9aa096d021bfb18e222f65dfea2869"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af84bc4ddbf660811caa74b1b1c7530f2"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#af84bc4ddbf660811caa74b1b1c7530f2">reference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a></td></tr>
<tr class="separator:af84bc4ddbf660811caa74b1b1c7530f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5cc7cf43685d32c4532151435f0acfa"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ab5cc7cf43685d32c4532151435f0acfa">const_reference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a></td></tr>
<tr class="separator:ab5cc7cf43685d32c4532151435f0acfa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac68c74ca15842976d265ae8164c0ebb7"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ac68c74ca15842976d265ae8164c0ebb7">pointer</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a></td></tr>
<tr class="separator:ac68c74ca15842976d265ae8164c0ebb7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a74d7ff046d692f208384113f55c54cf1"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a74d7ff046d692f208384113f55c54cf1">const_pointer</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a></td></tr>
<tr class="separator:a74d7ff046d692f208384113f55c54cf1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e713799b554d943d599c04e33da6643"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8e713799b554d943d599c04e33da6643">iterator</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a></td></tr>
<tr class="separator:a8e713799b554d943d599c04e33da6643"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8d8b74280204e0d3ac05fdb0e0423d90"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8d8b74280204e0d3ac05fdb0e0423d90">const_iterator</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a></td></tr>
<tr class="separator:a8d8b74280204e0d3ac05fdb0e0423d90"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abfa8a6dff52fd8a068da221bca705e02"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#abfa8a6dff52fd8a068da221bca705e02">reverse_iterator</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a></td></tr>
<tr class="separator:abfa8a6dff52fd8a068da221bca705e02"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a533fd802d70d0b1622cbc4e142f7f446"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a533fd802d70d0b1622cbc4e142f7f446">const_reverse_iterator</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a></td></tr>
<tr class="separator:a533fd802d70d0b1622cbc4e142f7f446"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:adca9e0bfc6bec4c47db6b4cb1ba3f693"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#adca9e0bfc6bec4c47db6b4cb1ba3f693">Array</a> ()=default</td></tr>
<tr class="separator:adca9e0bfc6bec4c47db6b4cb1ba3f693"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab271b77f1c13cb32617bc822deefc8d6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ab271b77f1c13cb32617bc822deefc8d6">Array</a> (std::initializer_list&lt; T &gt; list)</td></tr>
<tr class="separator:ab271b77f1c13cb32617bc822deefc8d6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2ba63e166ba8b77dc62b3a01b34e5330"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2ba63e166ba8b77dc62b3a01b34e5330">Array</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> const &amp;arr)=default</td></tr>
<tr class="separator:a2ba63e166ba8b77dc62b3a01b34e5330"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a95ae132a7378240b2eeadb19f7cee568"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a95ae132a7378240b2eeadb19f7cee568">Array</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> &amp;&amp;arr)=default</td></tr>
<tr class="separator:a95ae132a7378240b2eeadb19f7cee568"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8b21cfd0a6608aefaef606d1df918a7c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8b21cfd0a6608aefaef606d1df918a7c">~Array</a> ()=default</td></tr>
<tr class="separator:a8b21cfd0a6608aefaef606d1df918a7c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a44a5690339531da481afc1a5eadf901f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a44a5690339531da481afc1a5eadf901f">get</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> index)</td></tr>
<tr class="separator:a44a5690339531da481afc1a5eadf901f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aad44c8af85f19b2bef0515cc1855eff5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#aad44c8af85f19b2bef0515cc1855eff5">get</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> index) const </td></tr>
<tr class="separator:aad44c8af85f19b2bef0515cc1855eff5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3237517819984c8ee33207ea2b8e556b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3237517819984c8ee33207ea2b8e556b">getData</a> ()</td></tr>
<tr class="separator:a3237517819984c8ee33207ea2b8e556b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a251b1a1d6de33118b63a1b543fba93fa"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a251b1a1d6de33118b63a1b543fba93fa">getData</a> () const </td></tr>
<tr class="separator:a251b1a1d6de33118b63a1b543fba93fa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abbf5717e20eb223fd091d424e75b266d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#abbf5717e20eb223fd091d424e75b266d">getFront</a> ()</td></tr>
<tr class="separator:abbf5717e20eb223fd091d424e75b266d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab17c0c088722c5d658bb06d8ea839d30"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ab17c0c088722c5d658bb06d8ea839d30">getFront</a> () const </td></tr>
<tr class="separator:ab17c0c088722c5d658bb06d8ea839d30"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9daeee05b72f1d8c624910b27cc4e436"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9daeee05b72f1d8c624910b27cc4e436">getLast</a> ()</td></tr>
<tr class="separator:a9daeee05b72f1d8c624910b27cc4e436"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abdb4ed7bba3fa1fe0e34360e111d098f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#abdb4ed7bba3fa1fe0e34360e111d098f">getLast</a> () const </td></tr>
<tr class="separator:abdb4ed7bba3fa1fe0e34360e111d098f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a014e1b208f5fda5335ea4b11e8f9c9e4"><td class="memItemLeft" align="right" valign="top">constexpr bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a014e1b208f5fda5335ea4b11e8f9c9e4">isEmpty</a> () const </td></tr>
<tr class="separator:a014e1b208f5fda5335ea4b11e8f9c9e4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a99955b3454bc84deb2aa69f732b98b22"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a99955b3454bc84deb2aa69f732b98b22">getSize</a> () const </td></tr>
<tr class="separator:a99955b3454bc84deb2aa69f732b98b22"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a320f2444368d3c88aaa056f36f134558"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a320f2444368d3c88aaa056f36f134558">getMaxSize</a> () const </td></tr>
<tr class="separator:a320f2444368d3c88aaa056f36f134558"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a370a4e484cee21247a74334eef4d2b2d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a370a4e484cee21247a74334eef4d2b2d">begin</a> ()</td></tr>
<tr class="separator:a370a4e484cee21247a74334eef4d2b2d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a06764fc28ee8657256b253e4e2d1426f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a06764fc28ee8657256b253e4e2d1426f">begin</a> () const </td></tr>
<tr class="separator:a06764fc28ee8657256b253e4e2d1426f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adcf509c9cddaf2564dc2794bb72e8819"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#adcf509c9cddaf2564dc2794bb72e8819">cbegin</a> () const </td></tr>
<tr class="separator:adcf509c9cddaf2564dc2794bb72e8819"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e8f848bcb413ba1ed1c2285e3a88245"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a0e8f848bcb413ba1ed1c2285e3a88245">end</a> ()</td></tr>
<tr class="separator:a0e8f848bcb413ba1ed1c2285e3a88245"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3345445d1a17642d1d7ee7accb864ce1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3345445d1a17642d1d7ee7accb864ce1">end</a> () const </td></tr>
<tr class="separator:a3345445d1a17642d1d7ee7accb864ce1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeed554b8f663e9cc267561cf43a630ad"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#aeed554b8f663e9cc267561cf43a630ad">cend</a> () const </td></tr>
<tr class="separator:aeed554b8f663e9cc267561cf43a630ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61ee3b447d3335c18bdd833a5debc3a0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a61ee3b447d3335c18bdd833a5debc3a0">rbegin</a> ()</td></tr>
<tr class="separator:a61ee3b447d3335c18bdd833a5debc3a0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8b5556e668fa54a50c3f30bb29c2b431"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8b5556e668fa54a50c3f30bb29c2b431">rbegin</a> () const </td></tr>
<tr class="separator:a8b5556e668fa54a50c3f30bb29c2b431"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab6838cd211a43b7987d4f4ef2504d36e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ab6838cd211a43b7987d4f4ef2504d36e">crbegin</a> () const </td></tr>
<tr class="separator:ab6838cd211a43b7987d4f4ef2504d36e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0406aa5d43b160d9d733897906fcdb6d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a0406aa5d43b160d9d733897906fcdb6d">rend</a> ()</td></tr>
<tr class="separator:a0406aa5d43b160d9d733897906fcdb6d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a00e78dfd53d0b91167e778d99ca47e4b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a00e78dfd53d0b91167e778d99ca47e4b">rend</a> () const </td></tr>
<tr class="separator:a00e78dfd53d0b91167e778d99ca47e4b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace8d0009f02de8e75038ca6802542503"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ace8d0009f02de8e75038ca6802542503">crend</a> () const </td></tr>
<tr class="separator:ace8d0009f02de8e75038ca6802542503"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a24c150391274823dc07b349fbb58ea1b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a24c150391274823dc07b349fbb58ea1b">fill</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> value)</td></tr>
<tr class="separator:a24c150391274823dc07b349fbb58ea1b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a72ed3c0b6c1ccbf335d9ef26c0e7e074"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a72ed3c0b6c1ccbf335d9ef26c0e7e074">swap</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> &amp;arr) noexcept</td></tr>
<tr class="separator:a72ed3c0b6c1ccbf335d9ef26c0e7e074"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8dc6a4ea97517e06511abfc0fc9e173f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8dc6a4ea97517e06511abfc0fc9e173f">operator[]</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> index)</td></tr>
<tr class="separator:a8dc6a4ea97517e06511abfc0fc9e173f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aef8119488c41ba1d40a5f3c0b92e397e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#aef8119488c41ba1d40a5f3c0b92e397e">operator[]</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> index) const </td></tr>
<tr class="separator:aef8119488c41ba1d40a5f3c0b92e397e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adbd441f61e6a9784dc1e7c1055639738"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#adbd441f61e6a9784dc1e7c1055639738">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> const &amp;arr)=default</td></tr>
<tr class="separator:adbd441f61e6a9784dc1e7c1055639738"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae98007f6d8933d8b91d9e59767887684"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ae98007f6d8933d8b91d9e59767887684">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> &amp;&amp;arr)=default</td></tr>
<tr class="separator:ae98007f6d8933d8b91d9e59767887684"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac3841ae70203b4f1d773a9fe65020970"><td class="memTemplParams" colspan="2">template&lt;class K  = T, typename Utility::UseIfNotTriviallyCopyable&lt; K &gt;  = 0&gt; </td></tr>
<tr class="memitem:ac3841ae70203b4f1d773a9fe65020970"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ac3841ae70203b4f1d773a9fe65020970">operator==</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> const &amp;arr) const </td></tr>
<tr class="separator:ac3841ae70203b4f1d773a9fe65020970"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac3841ae70203b4f1d773a9fe65020970"><td class="memTemplParams" colspan="2">template&lt;class K  = T, typename Utility::UseIfTriviallyCopyable&lt; K &gt;  = 0&gt; </td></tr>
<tr class="memitem:ac3841ae70203b4f1d773a9fe65020970"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ac3841ae70203b4f1d773a9fe65020970">operator==</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> const &amp;arr) const </td></tr>
<tr class="separator:ac3841ae70203b4f1d773a9fe65020970"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acdf188605ad6e9c864aa034bd8e8b4d7"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#acdf188605ad6e9c864aa034bd8e8b4d7">operator!=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> const &amp;arr) const </td></tr>
<tr class="separator:acdf188605ad6e9c864aa034bd8e8b4d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad8ecae20e4a7da25f9067f2c9011133f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___string_8hpp.php#a20410cefd428aefdf41f418a1e489d66">String</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ad8ecae20e4a7da25f9067f2c9011133f">toString</a> () const </td></tr>
<tr class="separator:ad8ecae20e4a7da25f9067f2c9011133f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_utility_1_1_stringable"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_utility_1_1_stringable')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_stringable.php">NRE::Utility::Stringable&lt; Array&lt; T, Size &gt; &gt;</a></td></tr>
<tr class="memitem:a858907f8126e9c210854ddb659dd17ee inherit pub_methods_class_n_r_e_1_1_utility_1_1_stringable"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___string_8hpp.php#a20410cefd428aefdf41f418a1e489d66">String</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_stringable.php#a858907f8126e9c210854ddb659dd17ee">toString</a> () const</td></tr>
<tr class="separator:a858907f8126e9c210854ddb659dd17ee inherit pub_methods_class_n_r_e_1_1_utility_1_1_stringable"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, std::size_t Size&gt;<br />
class NRE::Utility::Array&lt; T, Size &gt;</h3>

<p>A fixed size array. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a8d8b74280204e0d3ac05fdb0e0423d90"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8d8b74280204e0d3ac05fdb0e0423d90">const_iterator</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a74d7ff046d692f208384113f55c54cf1"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a74d7ff046d692f208384113f55c54cf1">const_pointer</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="ab5cc7cf43685d32c4532151435f0acfa"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ab5cc7cf43685d32c4532151435f0acfa">const_reference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a533fd802d70d0b1622cbc4e142f7f446"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a533fd802d70d0b1622cbc4e142f7f446">const_reverse_iterator</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a1d9c3cedc358c6fa37ead43cbbf39eec"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Immuable random access iterator </p>

</div>
</div>
<a class="anchor" id="a2904cfdc42b306da7b6bbdebc948f3b0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a> =  const <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a>*</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The allocated type const pointer </p>

</div>
</div>
<a class="anchor" id="a21b7b2c6b0d2cafb542c719c27f26418"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> const&amp;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The allocated type const reference </p>

</div>
</div>
<a class="anchor" id="a77341af327bf71857307ee0bcbb4a33a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a> =  std::reverse_iterator&lt;<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a>&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Immuable reverse random access iterator </p>

</div>
</div>
<a class="anchor" id="a3e9aa096d021bfb18e222f65dfea2869"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3e9aa096d021bfb18e222f65dfea2869">difference_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a13503755383ed207497411583179745a">DifferenceType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a13503755383ed207497411583179745a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a13503755383ed207497411583179745a">DifferenceType</a> =  std::ptrdiff_t</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The object's difference type </p>

</div>
</div>
<a class="anchor" id="a1caa63883daa72f86cd6e912fbc62994"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Mutable random access iterator </p>

</div>
</div>
<a class="anchor" id="a8e713799b554d943d599c04e33da6643"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8e713799b554d943d599c04e33da6643">iterator</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a3a473b201017e3513b1c05061cbd5223"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a>*</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The allocated type pointer </p>

</div>
</div>
<a class="anchor" id="ac68c74ca15842976d265ae8164c0ebb7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#ac68c74ca15842976d265ae8164c0ebb7">pointer</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="afa251a0df0a73baae67d39177cfaa90f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a>&amp;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The allocated type reference </p>

</div>
</div>
<a class="anchor" id="af84bc4ddbf660811caa74b1b1c7530f2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#af84bc4ddbf660811caa74b1b1c7530f2">reference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="abfa8a6dff52fd8a068da221bca705e02"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#abfa8a6dff52fd8a068da221bca705e02">reverse_iterator</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a9f466da2cdfc8b3c07b9abf097d93acb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a> =  std::reverse_iterator&lt;<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a>&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Mutable reverse random access iterator </p>

</div>
</div>
<a class="anchor" id="a54963e0f1da053764235962bf9e5d000"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a54963e0f1da053764235962bf9e5d000">size_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a64b9ba4cfe847976b5a57605dde8f889"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> =  std::size_t</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The object's size type </p>

</div>
</div>
<a class="anchor" id="a8de99b6b188fe6f33a7335e7754b441e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a8de99b6b188fe6f33a7335e7754b441e">value_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a069bbb740098037643c0cb7712ef4b21"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a069bbb740098037643c0cb7712ef4b21">ValueType</a> =  T</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The container's allocated type </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="adca9e0bfc6bec4c47db6b4cb1ba3f693"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the default array </p>

</div>
</div>
<a class="anchor" id="ab271b77f1c13cb32617bc822deefc8d6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> </td>
          <td>(</td>
          <td class="paramtype">std::initializer_list&lt; T &gt;&#160;</td>
          <td class="paramname"><em>list</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Cosntruct the array from a list </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">list</td><td>the list of value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2ba63e166ba8b77dc62b3a01b34e5330"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; const &amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy arr into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the array to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a95ae132a7378240b2eeadb19f7cee568"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move arr into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the array to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8b21cfd0a6608aefaef606d1df918a7c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php" title="A fixed size array. ">Array</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a370a4e484cee21247a74334eef4d2b2d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>an iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a06764fc28ee8657256b253e4e2d1426f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="adcf509c9cddaf2564dc2794bb72e8819"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::cbegin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="aeed554b8f663e9cc267561cf43a630ad"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::cend </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="ab6838cd211a43b7987d4f4ef2504d36e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::crbegin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const reverse iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="ace8d0009f02de8e75038ca6802542503"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::crend </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const reverse iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a0e8f848bcb413ba1ed1c2285e3a88245"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1caa63883daa72f86cd6e912fbc62994">Iterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>an iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a3345445d1a17642d1d7ee7accb864ce1"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a1d9c3cedc358c6fa37ead43cbbf39eec">ConstIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a24c150391274823dc07b349fbb58ea1b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::fill </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a>&#160;</td>
          <td class="paramname"><em>value</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Fill the array with the same value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">value</td><td>the value to fill the array with </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a44a5690339531da481afc1a5eadf901f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::get </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access a particular element with bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the element index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding element </dd></dl>

</div>
</div>
<a class="anchor" id="aad44c8af85f19b2bef0515cc1855eff5"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::get </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access a particular element with bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the element index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding element </dd></dl>

</div>
</div>
<a class="anchor" id="a3237517819984c8ee33207ea2b8e556b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a3a473b201017e3513b1c05061cbd5223">Pointer</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal data array </dd></dl>

</div>
</div>
<a class="anchor" id="a251b1a1d6de33118b63a1b543fba93fa"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a2904cfdc42b306da7b6bbdebc948f3b0">ConstPointer</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal data array </dd></dl>

</div>
</div>
<a class="anchor" id="abbf5717e20eb223fd091d424e75b266d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getFront </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the first element </dd></dl>

</div>
</div>
<a class="anchor" id="ab17c0c088722c5d658bb06d8ea839d30"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getFront </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a9daeee05b72f1d8c624910b27cc4e436"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getLast </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the last element </dd></dl>

</div>
</div>
<a class="anchor" id="abdb4ed7bba3fa1fe0e34360e111d098f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getLast </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the last element </dd></dl>

</div>
</div>
<a class="anchor" id="a320f2444368d3c88aaa056f36f134558"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getMaxSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the maximum array size </dd></dl>

</div>
</div>
<a class="anchor" id="a99955b3454bc84deb2aa69f732b98b22"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::getSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the array size </dd></dl>

</div>
</div>
<a class="anchor" id="a014e1b208f5fda5335ea4b11e8f9c9e4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">constexpr bool <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::isEmpty </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the array is empty </dd></dl>

</div>
</div>
<a class="anchor" id="acdf188605ad6e9c864aa034bd8e8b4d7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator!= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; const &amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inequality test between this and arr </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the other array </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test result </dd></dl>

</div>
</div>
<a class="anchor" id="adbd441f61e6a9784dc1e7c1055639738"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; const &amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of arr into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the array to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ae98007f6d8933d8b91d9e59767887684"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of arr into this, leaving o empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the array to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ac3841ae70203b4f1d773a9fe65020970"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<div class="memtemplate">
template&lt;class K  = T, typename Utility::UseIfNotTriviallyCopyable&lt; K &gt;  = 0&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; const &amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Equality test between this and arr </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the other array </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test result </dd></dl>

</div>
</div>
<a class="anchor" id="ac3841ae70203b4f1d773a9fe65020970"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<div class="memtemplate">
template&lt;class K  = T, typename Utility::UseIfTriviallyCopyable&lt; K &gt;  = 0&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; const &amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Equality test between this and arr </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the other array </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test result </dd></dl>

</div>
</div>
<a class="anchor" id="a8dc6a4ea97517e06511abfc0fc9e173f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator[] </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access a particular element without bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the element index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding element </dd></dl>

</div>
</div>
<a class="anchor" id="aef8119488c41ba1d40a5f3c0b92e397e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a21b7b2c6b0d2cafb542c719c27f26418">ConstReference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::operator[] </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a64b9ba4cfe847976b5a57605dde8f889">SizeType</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access a particular element without bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the element index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding element </dd></dl>

</div>
</div>
<a class="anchor" id="a61ee3b447d3335c18bdd833a5debc3a0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::rbegin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a reverse iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a8b5556e668fa54a50c3f30bb29c2b431"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::rbegin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const reverse iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a0406aa5d43b160d9d733897906fcdb6d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">ReverseIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::rend </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a reverse iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a00e78dfd53d0b91167e778d99ca47e4b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a77341af327bf71857307ee0bcbb4a33a">ConstReverseIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::rend </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const reverse iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a72ed3c0b6c1ccbf335d9ef26c0e7e074"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::swap </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">Array</a>&lt; T, Size &gt; &amp;&#160;</td>
          <td class="paramname"><em>arr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Swap this data with arr data </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arr</td><td>the container to swap with </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad8ecae20e4a7da25f9067f2c9011133f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , std::size_t Size&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___string_8hpp.php#a20410cefd428aefdf41f418a1e489d66">String</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php">NRE::Utility::Array</a>&lt; T, Size &gt;::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the object into a string representation </p><dl class="section return"><dt>Returns</dt><dd>the converted object </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Array/<a class="el" href="_n_r_e___array_8hpp_source.php">NRE_Array.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
