<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Detail::HashTableInner::BucketEntry&lt; ValueType, StoreHash &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><b>Detail</b></li><li class="navelem"><b>HashTableInner</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Detail::HashTableInner::BucketEntry&lt; ValueType, StoreHash &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A bucket entry used as the hash table elements.  
 <a href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::Detail::HashTableInner::BucketEntry&lt; ValueType, StoreHash &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.png" usemap="#NRE::Utility::Detail::HashTableInner::BucketEntry_3C_20ValueType_2C_20StoreHash_20_3E_map" alt=""/>
  <map id="NRE::Utility::Detail::HashTableInner::BucketEntry_3C_20ValueType_2C_20StoreHash_20_3E_map" name="NRE::Utility::Detail::HashTableInner::BucketEntry&lt; ValueType, StoreHash &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php" title="Used to store the key hash, or not depending on the template value. " alt="NRE::Utility::Detail::HashTableInner::BucketEntryHash&lt; StoreHash &gt;" shape="rect" coords="0,0,433,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a895531b44513ebdb95f578de601e4215"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> = std::int_least16_t</td></tr>
<tr class="separator:a895531b44513ebdb95f578de601e4215"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acc7c13f824817742fa3f7a881b01ec39"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#acc7c13f824817742fa3f7a881b01ec39">Storage</a> = typename std::aligned_storage&lt; sizeof(ValueType), alignof(ValueType)&gt;::type</td></tr>
<tr class="separator:acc7c13f824817742fa3f7a881b01ec39"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a6e868fffb8f9508d57edd56a7a1cd996"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a6e868fffb8f9508d57edd56a7a1cd996">BucketEntry</a> ()</td></tr>
<tr class="separator:a6e868fffb8f9508d57edd56a7a1cd996"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a45148cdf77333bb08b97b45a98db77eb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a45148cdf77333bb08b97b45a98db77eb">BucketEntry</a> (bool state)</td></tr>
<tr class="separator:a45148cdf77333bb08b97b45a98db77eb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61fe57baa0e79674bf13e09f6551cb94"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a61fe57baa0e79674bf13e09f6551cb94">BucketEntry</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> const &amp;bucket)</td></tr>
<tr class="separator:a61fe57baa0e79674bf13e09f6551cb94"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a492159873047f55886f0f0cb76cdb2ed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a492159873047f55886f0f0cb76cdb2ed">BucketEntry</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> &amp;&amp;bucket)</td></tr>
<tr class="separator:a492159873047f55886f0f0cb76cdb2ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae350c76f79a8c8b5244e3e6434afbc89"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#ae350c76f79a8c8b5244e3e6434afbc89">~BucketEntry</a> ()</td></tr>
<tr class="separator:ae350c76f79a8c8b5244e3e6434afbc89"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9dc2ca3e3845de6dce20eefc5bfc4b31"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a9dc2ca3e3845de6dce20eefc5bfc4b31">isEmpty</a> () const </td></tr>
<tr class="separator:a9dc2ca3e3845de6dce20eefc5bfc4b31"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a95930a7aac13b84d325476e76dfaafb9"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a95930a7aac13b84d325476e76dfaafb9">isLastBucket</a> () const </td></tr>
<tr class="separator:a95930a7aac13b84d325476e76dfaafb9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a991d68b6e0e87341348130150f9f29a0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a991d68b6e0e87341348130150f9f29a0">getDistanceToNext</a> () const </td></tr>
<tr class="separator:a991d68b6e0e87341348130150f9f29a0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9f215f2a7558134fb830b0e0a4c2c386"><td class="memItemLeft" align="right" valign="top">ValueType &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a9f215f2a7558134fb830b0e0a4c2c386">getData</a> ()</td></tr>
<tr class="separator:a9f215f2a7558134fb830b0e0a4c2c386"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8d61bab9b60223ebc37b4ecbb8cd28e0"><td class="memItemLeft" align="right" valign="top">ValueType const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a8d61bab9b60223ebc37b4ecbb8cd28e0">getData</a> () const </td></tr>
<tr class="separator:a8d61bab9b60223ebc37b4ecbb8cd28e0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5a4780ca3c405abf32d0bbd5596b5d30"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a5a4780ca3c405abf32d0bbd5596b5d30">setAsLastBucket</a> ()</td></tr>
<tr class="separator:a5a4780ca3c405abf32d0bbd5596b5d30"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abfdbc23365b61e0c8bf8cdba8147a472"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#abfdbc23365b61e0c8bf8cdba8147a472">setData</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> distance, <a class="el" href="_n_r_e___hash_table_8hpp.php#a168c8c9ca451c0f72cbabdbb96d2b43c">TruncatedHash</a> h, ValueType &amp;&amp;newData)</td></tr>
<tr class="separator:abfdbc23365b61e0c8bf8cdba8147a472"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a0d81132cda79e42bd073213b3064dd"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a3a0d81132cda79e42bd073213b3064dd">clear</a> ()</td></tr>
<tr class="separator:a3a0d81132cda79e42bd073213b3064dd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8f9abaddd05f914c9294ff51c4538af0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a8f9abaddd05f914c9294ff51c4538af0">swapWithData</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> &amp;distance, <a class="el" href="_n_r_e___hash_table_8hpp.php#a168c8c9ca451c0f72cbabdbb96d2b43c">TruncatedHash</a> &amp;h, ValueType &amp;newData)</td></tr>
<tr class="separator:a8f9abaddd05f914c9294ff51c4538af0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a93db0f9357ef0b4d2325659625c2112c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a93db0f9357ef0b4d2325659625c2112c">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> const &amp;bucket)</td></tr>
<tr class="separator:a93db0f9357ef0b4d2325659625c2112c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad00df9d4e97740e6a8173a20843ca83b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#ad00df9d4e97740e6a8173a20843ca83b">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> &amp;&amp;bucket)</td></tr>
<tr class="separator:ad00df9d4e97740e6a8173a20843ca83b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php">NRE::Utility::Detail::HashTableInner::BucketEntryHash&lt; StoreHash &gt;</a></td></tr>
<tr class="memitem:ae266a9109d5ab3a704f091742b9516f3 inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php#ae266a9109d5ab3a704f091742b9516f3">bucketHashEquals</a> (std::size_t) const </td></tr>
<tr class="separator:ae266a9109d5ab3a704f091742b9516f3 inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af22bd72c98817a153f5e3220bc4c4c13 inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___hash_table_8hpp.php#a168c8c9ca451c0f72cbabdbb96d2b43c">TruncatedHash</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php#af22bd72c98817a153f5e3220bc4c4c13">getTruncatedHash</a> () const </td></tr>
<tr class="separator:af22bd72c98817a153f5e3220bc4c4c13 inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a73e78186902753d02f4436532f25e584"><td class="memItemLeft" align="right" valign="top">static const <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a73e78186902753d02f4436532f25e584">EMPTY_BUCKET_DISTANCE</a> = -1</td></tr>
<tr class="separator:a73e78186902753d02f4436532f25e584"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php">NRE::Utility::Detail::HashTableInner::BucketEntryHash&lt; StoreHash &gt;</a></td></tr>
<tr class="memitem:a6829b7702a4acca3b157a67b17eff6aa inherit pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php#a6829b7702a4acca3b157a67b17eff6aa">setHash</a> (<a class="el" href="_n_r_e___hash_table_8hpp.php#a168c8c9ca451c0f72cbabdbb96d2b43c">TruncatedHash</a>)</td></tr>
<tr class="separator:a6829b7702a4acca3b157a67b17eff6aa inherit pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class ValueType, bool StoreHash&gt;<br />
class NRE::Utility::Detail::HashTableInner::BucketEntry&lt; ValueType, StoreHash &gt;</h3>

<p>A bucket entry used as the hash table elements. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a895531b44513ebdb95f578de601e4215"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> =  std::int_least16_t</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The bucket distance type </p>

</div>
</div>
<a class="anchor" id="acc7c13f824817742fa3f7a881b01ec39"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#acc7c13f824817742fa3f7a881b01ec39">Storage</a> =  typename std::aligned_storage&lt;sizeof(ValueType), alignof(ValueType)&gt;::type</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The bucket internal storage type </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a6e868fffb8f9508d57edd56a7a1cd996"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty bucket </p>

</div>
</div>
<a class="anchor" id="a45148cdf77333bb08b97b45a98db77eb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty bucket with user defined last marker </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">state</td><td>tell if the bucket is the last </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a61fe57baa0e79674bf13e09f6551cb94"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; const &amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a492159873047f55886f0f0cb76cdb2ed"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae350c76f79a8c8b5244e3e6434afbc89"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php" title="A bucket entry used as the hash table elements. ">BucketEntry</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a3a0d81132cda79e42bd073213b3064dd"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::clear </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Clear the bucket data if not empty </p>

</div>
</div>
<a class="anchor" id="a9f215f2a7558134fb830b0e0a4c2c386"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">ValueType&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the bucket data </dd></dl>

</div>
</div>
<a class="anchor" id="a8d61bab9b60223ebc37b4ecbb8cd28e0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">ValueType const&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the bucket data </dd></dl>

</div>
</div>
<a class="anchor" id="a991d68b6e0e87341348130150f9f29a0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getDistanceToNext </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the distance to the next bucket </dd></dl>

</div>
</div>
<a class="anchor" id="a9dc2ca3e3845de6dce20eefc5bfc4b31"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::isEmpty </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the bucket is empty </dd></dl>

</div>
</div>
<a class="anchor" id="a95930a7aac13b84d325476e76dfaafb9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::isLastBucket </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the bucket is the last </dd></dl>

</div>
</div>
<a class="anchor" id="a93db0f9357ef0b4d2325659625c2112c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; const &amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ad00df9d4e97740e6a8173a20843ca83b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a5a4780ca3c405abf32d0bbd5596b5d30"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::setAsLastBucket </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set this as the last bucket </p>

</div>
</div>
<a class="anchor" id="abfdbc23365b61e0c8bf8cdba8147a472"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::setData </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a>&#160;</td>
          <td class="paramname"><em>distance</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="_n_r_e___hash_table_8hpp.php#a168c8c9ca451c0f72cbabdbb96d2b43c">TruncatedHash</a>&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ValueType &amp;&amp;&#160;</td>
          <td class="paramname"><em>newData</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the bucket data, must be empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">distance</td><td>the distance to the next bucket </td></tr>
    <tr><td class="paramname">h</td><td>the new truncated hash </td></tr>
    <tr><td class="paramname">newData</td><td>the data to set </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8f9abaddd05f914c9294ff51c4538af0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::swapWithData </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> &amp;&#160;</td>
          <td class="paramname"><em>distance</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="_n_r_e___hash_table_8hpp.php#a168c8c9ca451c0f72cbabdbb96d2b43c">TruncatedHash</a> &amp;&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ValueType &amp;&#160;</td>
          <td class="paramname"><em>newData</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Swap the bucket data with given one </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">distance</td><td>the distance to the next bucket </td></tr>
    <tr><td class="paramname">h</td><td>the new truncated hash </td></tr>
    <tr><td class="paramname">newData</td><td>the data to set </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a73e78186902753d02f4436532f25e584"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a895531b44513ebdb95f578de601e4215">DistanceType</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php">NRE::Utility::Detail::HashTableInner::BucketEntry</a>&lt; ValueType, StoreHash &gt;::EMPTY_BUCKET_DISTANCE = -1</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The distance used to mark a bucket as empty </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Detail/HashTable/<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
