<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Observable Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_observable-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Observable Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Describe an observable object, coupled with observer.  
 <a href="class_n_r_e_1_1_utility_1_1_observable.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___observable_8hpp_source.php">NRE_Observable.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a7653496967f32e0e852c77dd18e2e48b"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a7653496967f32e0e852c77dd18e2e48b">Container</a> = <a class="el" href="_vector_2_n_r_e___vector_8hpp.php#a7315c147598f6aea0b1c709bdac0470d">Vector</a>&lt; <a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a> * &gt;</td></tr>
<tr class="separator:a7653496967f32e0e852c77dd18e2e48b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a429d9cdc5bb4b232e75a727676be02bf"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a> = typename <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#aedc34798595924837f67fe06ae52dde7">Container::Iterator</a></td></tr>
<tr class="separator:a429d9cdc5bb4b232e75a727676be02bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acd5ae58a1df83250687e1c594460c3a9"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> = typename <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#afd29351c483eaf1b8b1322463b1ae11f">Container::ConstIterator</a></td></tr>
<tr class="separator:acd5ae58a1df83250687e1c594460c3a9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a36ef23c9392524b4f64718505a870760"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">SizeType</a> = typename <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#ab312674a156498a72bd5e4aca800b098">Container::SizeType</a></td></tr>
<tr class="separator:a36ef23c9392524b4f64718505a870760"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a809470a00740d22093325490e0fe8bd2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a809470a00740d22093325490e0fe8bd2">Observable</a> ()</td></tr>
<tr class="separator:a809470a00740d22093325490e0fe8bd2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a76a439473b3fcdf77b90b787c9c8604b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a76a439473b3fcdf77b90b787c9c8604b">Observable</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> const &amp;o)=default</td></tr>
<tr class="separator:a76a439473b3fcdf77b90b787c9c8604b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab74ece998a1024536cfba3b165f41ed3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#ab74ece998a1024536cfba3b165f41ed3">Observable</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:ab74ece998a1024536cfba3b165f41ed3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c1f5eb43b26526d963b8f354d6efefd"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a0c1f5eb43b26526d963b8f354d6efefd">~Observable</a> ()=default</td></tr>
<tr class="separator:a0c1f5eb43b26526d963b8f354d6efefd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1710c29e14429e62216cec550183fb17"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a1710c29e14429e62216cec550183fb17">isChanged</a> () const </td></tr>
<tr class="separator:a1710c29e14429e62216cec550183fb17"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac57384199059d8393992578bbc6b9b34"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#ac57384199059d8393992578bbc6b9b34">add</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a> *o)</td></tr>
<tr class="separator:ac57384199059d8393992578bbc6b9b34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2318c3fe9ec88fe681a931110ff069a6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a2318c3fe9ec88fe681a931110ff069a6">remove</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a> *o)</td></tr>
<tr class="separator:a2318c3fe9ec88fe681a931110ff069a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f8a1f4ed189c374fd0d65c28ab77652"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a3f8a1f4ed189c374fd0d65c28ab77652">clear</a> ()</td></tr>
<tr class="separator:a3f8a1f4ed189c374fd0d65c28ab77652"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a34e29f2813b4d466ebceecaecd5c6a05"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">SizeType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a34e29f2813b4d466ebceecaecd5c6a05">getCount</a> () const </td></tr>
<tr class="separator:a34e29f2813b4d466ebceecaecd5c6a05"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae53ec28846ac7a5bf311dfe2fc9893bf"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#ae53ec28846ac7a5bf311dfe2fc9893bf">notifyAll</a> (void *arg=0)</td></tr>
<tr class="separator:ae53ec28846ac7a5bf311dfe2fc9893bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c9ededf87047f24fa5a7726f9612e26"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a1c9ededf87047f24fa5a7726f9612e26">begin</a> ()</td></tr>
<tr class="separator:a1c9ededf87047f24fa5a7726f9612e26"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a71be916bfce100d609f68bfc24417eaa"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a71be916bfce100d609f68bfc24417eaa">begin</a> () const </td></tr>
<tr class="separator:a71be916bfce100d609f68bfc24417eaa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a42e2e119214b1bebc0c1eeec020bddd6"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a42e2e119214b1bebc0c1eeec020bddd6">cbegin</a> () const </td></tr>
<tr class="separator:a42e2e119214b1bebc0c1eeec020bddd6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afc048fdbf499f9ed0a3e5b00e9249891"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#afc048fdbf499f9ed0a3e5b00e9249891">end</a> ()</td></tr>
<tr class="separator:afc048fdbf499f9ed0a3e5b00e9249891"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad53839d5b31a9f34d111e195f7db2570"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#ad53839d5b31a9f34d111e195f7db2570">end</a> () const </td></tr>
<tr class="separator:ad53839d5b31a9f34d111e195f7db2570"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9c013d58495e7b5aa03c0547361b7fc5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a9c013d58495e7b5aa03c0547361b7fc5">cend</a> () const </td></tr>
<tr class="separator:a9c013d58495e7b5aa03c0547361b7fc5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af2070c089e1fc97f47e9aca09999a23e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#af2070c089e1fc97f47e9aca09999a23e">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> const &amp;o)=default</td></tr>
<tr class="separator:af2070c089e1fc97f47e9aca09999a23e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b2eec1f2bda57f77b3a82e709965e6e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a7b2eec1f2bda57f77b3a82e709965e6e">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp;o)=default</td></tr>
<tr class="separator:a7b2eec1f2bda57f77b3a82e709965e6e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:ad95320e70b7fd3ffe2406423c6eab9fa"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#ad95320e70b7fd3ffe2406423c6eab9fa">setChanged</a> (bool state)</td></tr>
<tr class="separator:ad95320e70b7fd3ffe2406423c6eab9fa"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Describe an observable object, coupled with observer. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="acd5ae58a1df83250687e1c594460c3a9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">NRE::Utility::Observable::ConstIterator</a> =  typename <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#afd29351c483eaf1b8b1322463b1ae11f">Container::ConstIterator</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The observers const iterator </p>

</div>
</div>
<a class="anchor" id="a7653496967f32e0e852c77dd18e2e48b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a7653496967f32e0e852c77dd18e2e48b">NRE::Utility::Observable::Container</a> =  <a class="el" href="_vector_2_n_r_e___vector_8hpp.php#a7315c147598f6aea0b1c709bdac0470d">Vector</a>&lt;<a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a>*&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The observers container </p>

</div>
</div>
<a class="anchor" id="a429d9cdc5bb4b232e75a727676be02bf"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">NRE::Utility::Observable::Iterator</a> =  typename <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#aedc34798595924837f67fe06ae52dde7">Container::Iterator</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The observers iterator </p>

</div>
</div>
<a class="anchor" id="a36ef23c9392524b4f64718505a870760"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">NRE::Utility::Observable::SizeType</a> =  typename <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#ab312674a156498a72bd5e4aca800b098">Container::SizeType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The observable size type </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a809470a00740d22093325490e0fe8bd2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Utility::Observable::Observable </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a76a439473b3fcdf77b90b787c9c8604b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Utility::Observable::Observable </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> const &amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy o into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the observable to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab74ece998a1024536cfba3b165f41ed3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Utility::Observable::Observable </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move o into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the observable to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a0c1f5eb43b26526d963b8f354d6efefd"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual NRE::Utility::Observable::~Observable </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php" title="Describe an observable object, coupled with observer. ">Observable</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ac57384199059d8393992578bbc6b9b34"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Utility::Observable::add </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a> *&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Add an observer </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the observer to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1c9ededf87047f24fa5a7726f9612e26"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a> NRE::Utility::Observable::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>an iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a71be916bfce100d609f68bfc24417eaa"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> NRE::Utility::Observable::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a42e2e119214b1bebc0c1eeec020bddd6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> NRE::Utility::Observable::cbegin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a9c013d58495e7b5aa03c0547361b7fc5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> NRE::Utility::Observable::cend </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a3f8a1f4ed189c374fd0d65c28ab77652"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Utility::Observable::clear </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove all observers </p>

</div>
</div>
<a class="anchor" id="afc048fdbf499f9ed0a3e5b00e9249891"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a429d9cdc5bb4b232e75a727676be02bf">Iterator</a> NRE::Utility::Observable::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>an iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="ad53839d5b31a9f34d111e195f7db2570"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#acd5ae58a1df83250687e1c594460c3a9">ConstIterator</a> NRE::Utility::Observable::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a34e29f2813b4d466ebceecaecd5c6a05"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a36ef23c9392524b4f64718505a870760">SizeType</a> NRE::Utility::Observable::getCount </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the number of observer </dd></dl>

</div>
</div>
<a class="anchor" id="a1710c29e14429e62216cec550183fb17"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Utility::Observable::isChanged </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the changed state </dd></dl>

</div>
</div>
<a class="anchor" id="ae53ec28846ac7a5bf311dfe2fc9893bf"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Utility::Observable::notifyAll </td>
          <td>(</td>
          <td class="paramtype">void *&#160;</td>
          <td class="paramname"><em>arg</em> = <code>0</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Notify all observer if changes happened </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arg</td><td>the notification argument </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af2070c089e1fc97f47e9aca09999a23e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a>&amp; NRE::Utility::Observable::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> const &amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy o into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the observable to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a7b2eec1f2bda57f77b3a82e709965e6e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a>&amp; NRE::Utility::Observable::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php">Observable</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move o into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the observable to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a2318c3fe9ec88fe681a931110ff069a6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Utility::Observable::remove </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_observer.php">Observer</a> *&#160;</td>
          <td class="paramname"><em>o</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove an observer </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">o</td><td>the observer to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad95320e70b7fd3ffe2406423c6eab9fa"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Utility::Observable::setChanged </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Changed setter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">state</td><td>the new changed state </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Observable/<a class="el" href="_n_r_e___observable_8hpp_source.php">NRE_Observable.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
