<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::ForwardList&lt; T &gt;::ForwardIterator&lt; K &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">ForwardList</a></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::ForwardList&lt; T &gt;::ForwardIterator&lt; K &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Internal iterator for forward list.  
 <a href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___forward_list_8hpp_source.php">NRE_ForwardList.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:ac85e5c305650a528556aecd59fb65c1c"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac85e5c305650a528556aecd59fb65c1c"></a>
typedef std::ptrdiff_t&#160;</td><td class="memItemRight" valign="bottom"><b>difference_type</b></td></tr>
<tr class="separator:ac85e5c305650a528556aecd59fb65c1c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a32a0582b08e9648ddc6217ca075e85"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9a32a0582b08e9648ddc6217ca075e85"></a>
typedef K&#160;</td><td class="memItemRight" valign="bottom"><b>value_type</b></td></tr>
<tr class="separator:a9a32a0582b08e9648ddc6217ca075e85"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac204711aa9a853de3ad5e96a4ef17f12"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac204711aa9a853de3ad5e96a4ef17f12"></a>
typedef K *&#160;</td><td class="memItemRight" valign="bottom"><b>pointer</b></td></tr>
<tr class="separator:ac204711aa9a853de3ad5e96a4ef17f12"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad39b2cd5e5440ce81fa848fbc0906462"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad39b2cd5e5440ce81fa848fbc0906462"></a>
typedef K &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>reference</b></td></tr>
<tr class="separator:ad39b2cd5e5440ce81fa848fbc0906462"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12986765fd51681f053879c9c3194732"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a12986765fd51681f053879c9c3194732"></a>
typedef std::forward_iterator_tag&#160;</td><td class="memItemRight" valign="bottom"><b>iterator_category</b></td></tr>
<tr class="separator:a12986765fd51681f053879c9c3194732"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a92e428380a20b14b8af95fe0d6c7ac56"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a92e428380a20b14b8af95fe0d6c7ac56">ForwardIterator</a> ()=default</td></tr>
<tr class="separator:a92e428380a20b14b8af95fe0d6c7ac56"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a13c6c8301ec488e7f19384a592d9e587"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a13c6c8301ec488e7f19384a592d9e587">ForwardIterator</a> (NodeBase *node)</td></tr>
<tr class="separator:a13c6c8301ec488e7f19384a592d9e587"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2949495574bed32d8d683ea9637a719e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a2949495574bed32d8d683ea9637a719e">ForwardIterator</a> (const NodeBase *node)</td></tr>
<tr class="separator:a2949495574bed32d8d683ea9637a719e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12432c4c8216cce30a5ee1c1ade8f7a6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a12432c4c8216cce30a5ee1c1ade8f7a6">ForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a12432c4c8216cce30a5ee1c1ade8f7a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82b3fee333473efd55096bb3c4fb1f25"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a82b3fee333473efd55096bb3c4fb1f25">~ForwardIterator</a> ()=default</td></tr>
<tr class="separator:a82b3fee333473efd55096bb3c4fb1f25"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9161b028c0f302c911d54a6d38f3531b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a9161b028c0f302c911d54a6d38f3531b">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a9161b028c0f302c911d54a6d38f3531b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a415565fb8123e01b535c558129b29c27"><td class="memItemLeft" align="right" valign="top">K &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a415565fb8123e01b535c558129b29c27">operator*</a> () const </td></tr>
<tr class="separator:a415565fb8123e01b535c558129b29c27"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af2e7635ebf29682e5ad4a51c6016bbfe"><td class="memItemLeft" align="right" valign="top">K *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#af2e7635ebf29682e5ad4a51c6016bbfe">operator-&gt;</a> () const </td></tr>
<tr class="separator:af2e7635ebf29682e5ad4a51c6016bbfe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4772f1bdf4ce522e68637fdf92cc2b4d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a4772f1bdf4ce522e68637fdf92cc2b4d">operator++</a> ()</td></tr>
<tr class="separator:a4772f1bdf4ce522e68637fdf92cc2b4d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a70ac13cad3c81ba2407ecf5eb6d7bc31"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a70ac13cad3c81ba2407ecf5eb6d7bc31">operator++</a> (int)</td></tr>
<tr class="separator:a70ac13cad3c81ba2407ecf5eb6d7bc31"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0054b7032a951bc8b920eb97c4a132ec"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a0054b7032a951bc8b920eb97c4a132ec">operator==</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it) const </td></tr>
<tr class="separator:a0054b7032a951bc8b920eb97c4a132ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2a51aaf1eec5b75db4e68b7a4fd09abf"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php#a2a51aaf1eec5b75db4e68b7a4fd09abf">operator!=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it) const </td></tr>
<tr class="separator:a2a51aaf1eec5b75db4e68b7a4fd09abf"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:accea79489596e0532db7ae08f8757ca6"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="accea79489596e0532db7ae08f8757ca6"></a>
class&#160;</td><td class="memItemRight" valign="bottom"><b>ForwardList</b></td></tr>
<tr class="separator:accea79489596e0532db7ae08f8757ca6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
template&lt;class K&gt;<br />
class NRE::Utility::ForwardList&lt; T &gt;::ForwardIterator&lt; K &gt;</h3>

<p>Internal iterator for forward list. </p>
<p>Shortcut to hide Iterator implementation </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a92e428380a20b14b8af95fe0d6c7ac56"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor with nullptr node </p>

</div>
</div>
<a class="anchor" id="a13c6c8301ec488e7f19384a592d9e587"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">NodeBase *&#160;</td>
          <td class="paramname"><em>node</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">node</td><td>the iterator node </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2949495574bed32d8d683ea9637a719e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">const NodeBase *&#160;</td>
          <td class="paramname"><em>node</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">node</td><td>the iterator node </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a12432c4c8216cce30a5ee1c1ade8f7a6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a82b3fee333473efd55096bb3c4fb1f25"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php" title="Internal iterator for forward list. ">ForwardIterator</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a2a51aaf1eec5b75db4e68b7a4fd09abf"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator!= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inequality test between this and it </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the other iterator </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test result </dd></dl>

</div>
</div>
<a class="anchor" id="a415565fb8123e01b535c558129b29c27"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">K&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator* </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Dereference operator, allow access to the data </p><dl class="section return"><dt>Returns</dt><dd>the iterator data </dd></dl>

</div>
</div>
<a class="anchor" id="a4772f1bdf4ce522e68637fdf92cc2b4d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator++ </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Pre increment operator, access the next element </p><dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a70ac13cad3c81ba2407ecf5eb6d7bc31"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator++ </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Post increment operator, access the next element </p><dl class="section return"><dt>Returns</dt><dd>the iterator on the current element </dd></dl>

</div>
</div>
<a class="anchor" id="af2e7635ebf29682e5ad4a51c6016bbfe"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">K* <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator-&gt; </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Arrow dereference operator, allow access to the data </p><dl class="section return"><dt>Returns</dt><dd>the iterator data pointer </dd></dl>

</div>
</div>
<a class="anchor" id="a9161b028c0f302c911d54a6d38f3531b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a0054b7032a951bc8b920eb97c4a132ec"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class K &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list.php">NRE::Utility::ForwardList</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt;::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_forward_list_1_1_forward_iterator.php">ForwardIterator</a>&lt; K &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and it </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the other iterator </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test result </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/ForwardList/<a class="el" href="_n_r_e___forward_list_8hpp_source.php">NRE_ForwardList.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
