<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><b>Detail</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A bucket entry used as the hash table elements.  
 <a href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.png" usemap="#NRE::Utility::Detail::BucketEntry_3C_20ValueType_2C_20StoreHash_20_3E_map" alt=""/>
  <map id="NRE::Utility::Detail::BucketEntry_3C_20ValueType_2C_20StoreHash_20_3E_map" name="NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php" title="Used to store the key hash, or not depending on the template value. " alt="NRE::Utility::Detail::BucketEntryHash&lt; StoreHash &gt;" shape="rect" coords="0,0,338,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:af7c92dda203f3305de4e590909ff32f4"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af7c92dda203f3305de4e590909ff32f4"></a>
typedef std::int_least16_t&#160;</td><td class="memItemRight" valign="bottom"><b>DistanceType</b></td></tr>
<tr class="separator:af7c92dda203f3305de4e590909ff32f4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a979e827b908aad750d78034b579bc914"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a979e827b908aad750d78034b579bc914"></a>
typedef std::aligned_storage&lt; sizeof(ValueType), alignof(ValueType)&gt;::type&#160;</td><td class="memItemRight" valign="bottom"><b>Storage</b></td></tr>
<tr class="separator:a979e827b908aad750d78034b579bc914"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a753c02f3e137b75e754754304f0f8e32"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a753c02f3e137b75e754754304f0f8e32">BucketEntry</a> ()</td></tr>
<tr class="separator:a753c02f3e137b75e754754304f0f8e32"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5606e4b3d53eb79189edec14b1b651a4"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a5606e4b3d53eb79189edec14b1b651a4">BucketEntry</a> (bool state)</td></tr>
<tr class="separator:a5606e4b3d53eb79189edec14b1b651a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae904d88fd4387d5faf73f2f1040dece9"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#ae904d88fd4387d5faf73f2f1040dece9">BucketEntry</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> const &amp;bucket)</td></tr>
<tr class="separator:ae904d88fd4387d5faf73f2f1040dece9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abad3c49ed94e2d95f5b043d743225ca7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#abad3c49ed94e2d95f5b043d743225ca7">BucketEntry</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> &amp;&amp;bucket)</td></tr>
<tr class="separator:abad3c49ed94e2d95f5b043d743225ca7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3ae7cc0e4b8a95a881eeee75aefd576b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a3ae7cc0e4b8a95a881eeee75aefd576b">~BucketEntry</a> ()</td></tr>
<tr class="separator:a3ae7cc0e4b8a95a881eeee75aefd576b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a632987ad8cbbb52c78007c81cdd75b63"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a632987ad8cbbb52c78007c81cdd75b63">isEmpty</a> () const </td></tr>
<tr class="separator:a632987ad8cbbb52c78007c81cdd75b63"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8ed2728946b71f255a445d78f6e57ed7"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a8ed2728946b71f255a445d78f6e57ed7">isLastBucket</a> () const </td></tr>
<tr class="separator:a8ed2728946b71f255a445d78f6e57ed7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac0d7b65accda82311d88813896a8f15"><td class="memItemLeft" align="right" valign="top">DistanceType&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#aac0d7b65accda82311d88813896a8f15">getDistanceToNext</a> () const </td></tr>
<tr class="separator:aac0d7b65accda82311d88813896a8f15"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e0613268c80ce19ab95e5ca966ba336"><td class="memItemLeft" align="right" valign="top">ValueType &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a8e0613268c80ce19ab95e5ca966ba336">getData</a> ()</td></tr>
<tr class="separator:a8e0613268c80ce19ab95e5ca966ba336"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6a0d7a5fdef78241e0d6126ba579e0ce"><td class="memItemLeft" align="right" valign="top">ValueType const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a6a0d7a5fdef78241e0d6126ba579e0ce">getData</a> () const </td></tr>
<tr class="separator:a6a0d7a5fdef78241e0d6126ba579e0ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acae75c13940ea2d5cfd5579d63253916"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#acae75c13940ea2d5cfd5579d63253916">setAsLastBucket</a> ()</td></tr>
<tr class="separator:acae75c13940ea2d5cfd5579d63253916"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a697984f6cf8f34aa8670627bdab0bdab"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a697984f6cf8f34aa8670627bdab0bdab">setData</a> (DistanceType distance, TruncatedHash h, ValueType &amp;&amp;newData)</td></tr>
<tr class="separator:a697984f6cf8f34aa8670627bdab0bdab"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0052d0b421093bf5609cb13a0b9a19e9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a0052d0b421093bf5609cb13a0b9a19e9">clear</a> ()</td></tr>
<tr class="separator:a0052d0b421093bf5609cb13a0b9a19e9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20f4afca0d279783b2bb98c07fd10178"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#a20f4afca0d279783b2bb98c07fd10178">swapWithData</a> (DistanceType &amp;distance, TruncatedHash &amp;h, ValueType &amp;newData)</td></tr>
<tr class="separator:a20f4afca0d279783b2bb98c07fd10178"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad947b55675d7af985c6aa4463e0d9ccf"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#ad947b55675d7af985c6aa4463e0d9ccf">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> const &amp;bucket)</td></tr>
<tr class="separator:ad947b55675d7af985c6aa4463e0d9ccf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd0dac5051a38c9e39f6c18639f6a569"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#afd0dac5051a38c9e39f6c18639f6a569">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> &amp;&amp;bucket)</td></tr>
<tr class="separator:afd0dac5051a38c9e39f6c18639f6a569"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php">NRE::Utility::Detail::BucketEntryHash&lt; StoreHash &gt;</a></td></tr>
<tr class="memitem:a44bbda026b156df237763c94c030e5ae inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php#a44bbda026b156df237763c94c030e5ae">bucketHashEquals</a> (std::size_t) const </td></tr>
<tr class="separator:a44bbda026b156df237763c94c030e5ae inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad1dc8a5312f8fc3a6189564eb8df152c inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">TruncatedHash&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php#ad1dc8a5312f8fc3a6189564eb8df152c">getTruncatedHash</a> () const </td></tr>
<tr class="separator:ad1dc8a5312f8fc3a6189564eb8df152c inherit pub_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:abbcb1b8b41205bc789a169b6683aecc6"><td class="memItemLeft" align="right" valign="top">static const DistanceType&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php#abbcb1b8b41205bc789a169b6683aecc6">EMPTY_BUCKET_DISTANCE</a> = -1</td></tr>
<tr class="separator:abbcb1b8b41205bc789a169b6683aecc6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php">NRE::Utility::Detail::BucketEntryHash&lt; StoreHash &gt;</a></td></tr>
<tr class="memitem:a7610dfcbf24281cb5eff7b7f08e95c76 inherit pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash.php#a7610dfcbf24281cb5eff7b7f08e95c76">setHash</a> (TruncatedHash)</td></tr>
<tr class="separator:a7610dfcbf24281cb5eff7b7f08e95c76 inherit pro_methods_class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class ValueType, bool StoreHash&gt;<br />
class NRE::Utility::Detail::BucketEntry&lt; ValueType, StoreHash &gt;</h3>

<p>A bucket entry used as the hash table elements. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a753c02f3e137b75e754754304f0f8e32"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty bucket </p>

</div>
</div>
<a class="anchor" id="a5606e4b3d53eb79189edec14b1b651a4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty bucket with user defined last marker </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">state</td><td>tell if the bucket is the last </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae904d88fd4387d5faf73f2f1040dece9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; const &amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="abad3c49ed94e2d95f5b043d743225ca7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3ae7cc0e4b8a95a881eeee75aefd576b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php" title="A bucket entry used as the hash table elements. ">BucketEntry</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a0052d0b421093bf5609cb13a0b9a19e9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::clear </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Clear the bucket data if not empty </p>

</div>
</div>
<a class="anchor" id="a8e0613268c80ce19ab95e5ca966ba336"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">ValueType&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the bucket data </dd></dl>

</div>
</div>
<a class="anchor" id="a6a0d7a5fdef78241e0d6126ba579e0ce"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">ValueType const&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the bucket data </dd></dl>

</div>
</div>
<a class="anchor" id="aac0d7b65accda82311d88813896a8f15"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">DistanceType <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getDistanceToNext </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the distance to the next bucket </dd></dl>

</div>
</div>
<a class="anchor" id="a632987ad8cbbb52c78007c81cdd75b63"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::isEmpty </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the bucket is empty </dd></dl>

</div>
</div>
<a class="anchor" id="a8ed2728946b71f255a445d78f6e57ed7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::isLastBucket </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the bucket is the last </dd></dl>

</div>
</div>
<a class="anchor" id="ad947b55675d7af985c6aa4463e0d9ccf"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; const &amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="afd0dac5051a38c9e39f6c18639f6a569"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="acae75c13940ea2d5cfd5579d63253916"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::setAsLastBucket </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set this as the last bucket </p>

</div>
</div>
<a class="anchor" id="a697984f6cf8f34aa8670627bdab0bdab"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::setData </td>
          <td>(</td>
          <td class="paramtype">DistanceType&#160;</td>
          <td class="paramname"><em>distance</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">TruncatedHash&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ValueType &amp;&amp;&#160;</td>
          <td class="paramname"><em>newData</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the bucket data, must be empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">distance</td><td>the distance to the next bucket </td></tr>
    <tr><td class="paramname">h</td><td>the new truncated hash </td></tr>
    <tr><td class="paramname">newData</td><td>the data to set </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a20f4afca0d279783b2bb98c07fd10178"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::swapWithData </td>
          <td>(</td>
          <td class="paramtype">DistanceType &amp;&#160;</td>
          <td class="paramname"><em>distance</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">TruncatedHash &amp;&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ValueType &amp;&#160;</td>
          <td class="paramname"><em>newData</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Swap the bucket data with given one </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">distance</td><td>the distance to the next bucket </td></tr>
    <tr><td class="paramname">h</td><td>the new truncated hash </td></tr>
    <tr><td class="paramname">newData</td><td>the data to set </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="abbcb1b8b41205bc789a169b6683aecc6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const DistanceType <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_bucket_entry.php">NRE::Utility::Detail::BucketEntry</a>&lt; ValueType, StoreHash &gt;::EMPTY_BUCKET_DISTANCE = -1</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The distance used to mark a bucket as empty </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Detail/HashTable/<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
