<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Math: NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_bucket_entry-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A bucket entry used as the hash table elements.  
 <a href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_bucket_entry.png" usemap="#NRE::Utility::BucketEntry_3C_20ValueType_2C_20StoreHash_20_3E_map" alt=""/>
  <map id="NRE::Utility::BucketEntry_3C_20ValueType_2C_20StoreHash_20_3E_map" name="NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php" title="Used to store the key hash, or not depending on the template value. " alt="NRE::Utility::BucketEntryHash&lt; StoreHash &gt;" shape="rect" coords="0,0,300,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a3ed320057f2ad7611f6685f6d2954dbf"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3ed320057f2ad7611f6685f6d2954dbf"></a>
typedef std::int_least16_t&#160;</td><td class="memItemRight" valign="bottom"><b>DistanceType</b></td></tr>
<tr class="separator:a3ed320057f2ad7611f6685f6d2954dbf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac0fbb01a738029bfad6dd982da5f22b9"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac0fbb01a738029bfad6dd982da5f22b9"></a>
typedef std::aligned_storage&lt; sizeof(ValueType), alignof(ValueType)&gt;::type&#160;</td><td class="memItemRight" valign="bottom"><b>Storage</b></td></tr>
<tr class="separator:ac0fbb01a738029bfad6dd982da5f22b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a84fc56821cc153a9d0e7908ba3f729c6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a84fc56821cc153a9d0e7908ba3f729c6">BucketEntry</a> ()</td></tr>
<tr class="separator:a84fc56821cc153a9d0e7908ba3f729c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a130a66ff82bfb2640d0b5574036ffdfb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a130a66ff82bfb2640d0b5574036ffdfb">BucketEntry</a> (bool state)</td></tr>
<tr class="separator:a130a66ff82bfb2640d0b5574036ffdfb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4b796870d26f0547f61823803f7cc637"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a4b796870d26f0547f61823803f7cc637">BucketEntry</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> const &amp;bucket)</td></tr>
<tr class="separator:a4b796870d26f0547f61823803f7cc637"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ade0e9c2f08f57fc567433ada7ce770dc"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#ade0e9c2f08f57fc567433ada7ce770dc">BucketEntry</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> &amp;&amp;bucket)</td></tr>
<tr class="separator:ade0e9c2f08f57fc567433ada7ce770dc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf920402af50f4a9c6c7606420de8f11"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#adf920402af50f4a9c6c7606420de8f11">~BucketEntry</a> ()</td></tr>
<tr class="separator:adf920402af50f4a9c6c7606420de8f11"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a16a68a93ffc4a2df040db1987dfdcad2"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a16a68a93ffc4a2df040db1987dfdcad2">isEmpty</a> () const </td></tr>
<tr class="separator:a16a68a93ffc4a2df040db1987dfdcad2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a561f866defb9fac335bb71961a6185"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a8a561f866defb9fac335bb71961a6185">isLastBucket</a> () const </td></tr>
<tr class="separator:a8a561f866defb9fac335bb71961a6185"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6cd8a0f0faa075f231602ff5d62bf868"><td class="memItemLeft" align="right" valign="top">DistanceType&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a6cd8a0f0faa075f231602ff5d62bf868">getDistanceToNext</a> () const </td></tr>
<tr class="separator:a6cd8a0f0faa075f231602ff5d62bf868"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4c71f9d6079559245b4e76031cc717ec"><td class="memItemLeft" align="right" valign="top">ValueType &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a4c71f9d6079559245b4e76031cc717ec">getData</a> ()</td></tr>
<tr class="separator:a4c71f9d6079559245b4e76031cc717ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3c7706e4b1f93b61dc3cf22f64614e24"><td class="memItemLeft" align="right" valign="top">ValueType const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a3c7706e4b1f93b61dc3cf22f64614e24">getData</a> () const </td></tr>
<tr class="separator:a3c7706e4b1f93b61dc3cf22f64614e24"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab62abac1cc7a97018d8ed074caf82315"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#ab62abac1cc7a97018d8ed074caf82315">setAsLastBucket</a> ()</td></tr>
<tr class="separator:ab62abac1cc7a97018d8ed074caf82315"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a504da56b18c9c17e8fb5a232f1420b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a8a504da56b18c9c17e8fb5a232f1420b">setData</a> (DistanceType distance, TruncatedHash h, ValueType &amp;&amp;newData)</td></tr>
<tr class="separator:a8a504da56b18c9c17e8fb5a232f1420b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b2ec6028e7b2d2bb1197b01a10e7556"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a7b2ec6028e7b2d2bb1197b01a10e7556">clear</a> ()</td></tr>
<tr class="separator:a7b2ec6028e7b2d2bb1197b01a10e7556"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e545299519702f52cb4ecdc6d10318c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a8e545299519702f52cb4ecdc6d10318c">swapWithData</a> (DistanceType &amp;distance, TruncatedHash &amp;h, ValueType &amp;newData)</td></tr>
<tr class="separator:a8e545299519702f52cb4ecdc6d10318c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a95b0c1515d88bda0e43a228dbce95947"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a95b0c1515d88bda0e43a228dbce95947">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> const &amp;bucket)</td></tr>
<tr class="separator:a95b0c1515d88bda0e43a228dbce95947"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a23e53df15b64945c974493162ea5f9d1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a23e53df15b64945c974493162ea5f9d1">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> &amp;&amp;bucket)</td></tr>
<tr class="separator:a23e53df15b64945c974493162ea5f9d1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php">NRE::Utility::BucketEntryHash&lt; StoreHash &gt;</a></td></tr>
<tr class="memitem:a6a0f44c490c0f828d1377a231d1166d4 inherit pub_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php#a6a0f44c490c0f828d1377a231d1166d4">bucketHashEquals</a> (std::size_t) const </td></tr>
<tr class="separator:a6a0f44c490c0f828d1377a231d1166d4 inherit pub_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a649b8be8873d8550244a7656a98921e1 inherit pub_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">TruncatedHash&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php#a649b8be8873d8550244a7656a98921e1">getTruncatedHash</a> () const </td></tr>
<tr class="separator:a649b8be8873d8550244a7656a98921e1 inherit pub_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a0fef8d48cbabdbc2ad0f8f1bfeccbf9a"><td class="memItemLeft" align="right" valign="top">static const DistanceType&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php#a0fef8d48cbabdbc2ad0f8f1bfeccbf9a">EMPTY_BUCKET_DISTANCE</a> = -1</td></tr>
<tr class="separator:a0fef8d48cbabdbc2ad0f8f1bfeccbf9a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pro_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php">NRE::Utility::BucketEntryHash&lt; StoreHash &gt;</a></td></tr>
<tr class="memitem:ac5fb7ad7eaffbd1b53fb77c49a8e2722 inherit pro_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry_hash.php#ac5fb7ad7eaffbd1b53fb77c49a8e2722">setHash</a> (TruncatedHash)</td></tr>
<tr class="separator:ac5fb7ad7eaffbd1b53fb77c49a8e2722 inherit pro_methods_class_n_r_e_1_1_utility_1_1_bucket_entry_hash"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class ValueType, bool StoreHash&gt;<br />
class NRE::Utility::BucketEntry&lt; ValueType, StoreHash &gt;</h3>

<p>A bucket entry used as the hash table elements. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a84fc56821cc153a9d0e7908ba3f729c6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty bucket </p>

</div>
</div>
<a class="anchor" id="a130a66ff82bfb2640d0b5574036ffdfb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty bucket with user defined last marker </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">state</td><td>tell if the bucket is the last </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a4b796870d26f0547f61823803f7cc637"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; const &amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ade0e9c2f08f57fc567433ada7ce770dc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="adf920402af50f4a9c6c7606420de8f11"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php" title="A bucket entry used as the hash table elements. ">BucketEntry</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a7b2ec6028e7b2d2bb1197b01a10e7556"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::clear </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Clear the bucket data if not empty </p>

</div>
</div>
<a class="anchor" id="a4c71f9d6079559245b4e76031cc717ec"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">ValueType&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the bucket data </dd></dl>

</div>
</div>
<a class="anchor" id="a3c7706e4b1f93b61dc3cf22f64614e24"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">ValueType const&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getData </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the bucket data </dd></dl>

</div>
</div>
<a class="anchor" id="a6cd8a0f0faa075f231602ff5d62bf868"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">DistanceType <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::getDistanceToNext </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the distance to the next bucket </dd></dl>

</div>
</div>
<a class="anchor" id="a16a68a93ffc4a2df040db1987dfdcad2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::isEmpty </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the bucket is empty </dd></dl>

</div>
</div>
<a class="anchor" id="a8a561f866defb9fac335bb71961a6185"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::isLastBucket </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the bucket is the last </dd></dl>

</div>
</div>
<a class="anchor" id="a95b0c1515d88bda0e43a228dbce95947"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; const &amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a23e53df15b64945c974493162ea5f9d1"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">BucketEntry</a>&lt; ValueType, StoreHash &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>bucket</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move bucket into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">bucket</td><td>the bucket entry to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ab62abac1cc7a97018d8ed074caf82315"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::setAsLastBucket </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set this as the last bucket </p>

</div>
</div>
<a class="anchor" id="a8a504da56b18c9c17e8fb5a232f1420b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::setData </td>
          <td>(</td>
          <td class="paramtype">DistanceType&#160;</td>
          <td class="paramname"><em>distance</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">TruncatedHash&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ValueType &amp;&amp;&#160;</td>
          <td class="paramname"><em>newData</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the bucket data, must be empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">distance</td><td>the distance to the next bucket </td></tr>
    <tr><td class="paramname">h</td><td>the new truncated hash </td></tr>
    <tr><td class="paramname">newData</td><td>the data to set </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8e545299519702f52cb4ecdc6d10318c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::swapWithData </td>
          <td>(</td>
          <td class="paramtype">DistanceType &amp;&#160;</td>
          <td class="paramname"><em>distance</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">TruncatedHash &amp;&#160;</td>
          <td class="paramname"><em>h</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ValueType &amp;&#160;</td>
          <td class="paramname"><em>newData</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Swap the bucket data with given one </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">distance</td><td>the distance to the next bucket </td></tr>
    <tr><td class="paramname">h</td><td>the new truncated hash </td></tr>
    <tr><td class="paramname">newData</td><td>the data to set </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a0fef8d48cbabdbc2ad0f8f1bfeccbf9a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class ValueType, bool StoreHash&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const DistanceType <a class="el" href="class_n_r_e_1_1_utility_1_1_bucket_entry.php">NRE::Utility::BucketEntry</a>&lt; ValueType, StoreHash &gt;::EMPTY_BUCKET_DISTANCE = -1</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The distance used to mark a bucket as empty </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/HashTable/<a class="el" href="_n_r_e___hash_table_8hpp_source.php">NRE_HashTable.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
