<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Utility</b></li><li class="navelem"><b>Detail</b></li><li class="navelem"><b>ForwardListInner</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Internal iterator for forward list.  
 <a href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_detail_2_forward_list_2_n_r_e___forward_list_8hpp_source.php">NRE_ForwardList.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.png" usemap="#NRE::Utility::Detail::ForwardListInner::ForwardIterator_3C_20T_2C_20Category_20_3E_map" alt=""/>
  <map id="NRE::Utility::Detail::ForwardListInner::ForwardIterator_3C_20T_2C_20Category_20_3E_map" name="NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt;_map">
<area href="class_n_r_e_1_1_utility_1_1_iterator_traits.php" alt="NRE::Utility::IteratorTraits&lt; ForwardIterator&lt; T, Category &gt;, T, Category &gt;" shape="rect" coords="0,0,431,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a8ded24eb3c9d9bc29b950f7a2f026789"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a8ded24eb3c9d9bc29b950f7a2f026789">Traits</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php">IteratorTraits</a>&lt; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category &gt;, T, Category &gt;</td></tr>
<tr class="separator:a8ded24eb3c9d9bc29b950f7a2f026789"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a57a8c0ce2d71e964d460def04051c777"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a57a8c0ce2d71e964d460def04051c777">ValueType</a> = typename Traits::ValueType</td></tr>
<tr class="separator:a57a8c0ce2d71e964d460def04051c777"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75e3abc43993291c3a22a3825f7aae88"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a75e3abc43993291c3a22a3825f7aae88">Pointer</a> = typename Traits::Pointer</td></tr>
<tr class="separator:a75e3abc43993291c3a22a3825f7aae88"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a307a8034c92c8f7b67745a08093097f2"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">Reference</a> = typename Traits::Reference</td></tr>
<tr class="separator:a307a8034c92c8f7b67745a08093097f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c1bc7527aad881dfe71782163ea9abd"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a1c1bc7527aad881dfe71782163ea9abd">DifferenceType</a> = typename Traits::DifferenceType</td></tr>
<tr class="separator:a1c1bc7527aad881dfe71782163ea9abd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4bcca1d42c5ee414f0cca6685e080347"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a4bcca1d42c5ee414f0cca6685e080347">value_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a57a8c0ce2d71e964d460def04051c777">ValueType</a></td></tr>
<tr class="separator:a4bcca1d42c5ee414f0cca6685e080347"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab62d03403d1822e891106e4a94dcc287"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#ab62d03403d1822e891106e4a94dcc287">pointer</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a75e3abc43993291c3a22a3825f7aae88">Pointer</a></td></tr>
<tr class="separator:ab62d03403d1822e891106e4a94dcc287"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae4f322cf6dcbf1ba73fcbaa36822c4e6"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#ae4f322cf6dcbf1ba73fcbaa36822c4e6">reference</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">Reference</a></td></tr>
<tr class="separator:ae4f322cf6dcbf1ba73fcbaa36822c4e6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a838077f8b3bb80dd60f04bf48c055e46"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a838077f8b3bb80dd60f04bf48c055e46">difference_type</a> = <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a1c1bc7527aad881dfe71782163ea9abd">DifferenceType</a></td></tr>
<tr class="separator:a838077f8b3bb80dd60f04bf48c055e46"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5a23e28633e49aa6450d2ca2f0e3510f"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a5a23e28633e49aa6450d2ca2f0e3510f">iterator_category</a> = typename Traits::iterator_category</td></tr>
<tr class="separator:a5a23e28633e49aa6450d2ca2f0e3510f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a6f70da0e29614379e3a8de990f0c4b50"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a6f70da0e29614379e3a8de990f0c4b50">ForwardIterator</a> ()=default</td></tr>
<tr class="separator:a6f70da0e29614379e3a8de990f0c4b50"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aed19d64a2569875c956fdd595cd8c183"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#aed19d64a2569875c956fdd595cd8c183">ForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php">NodeBase</a> *node)</td></tr>
<tr class="separator:aed19d64a2569875c956fdd595cd8c183"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a54da5bb57bce5eb1f701b328cb771f5d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a54da5bb57bce5eb1f701b328cb771f5d">ForwardIterator</a> (const <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php">NodeBase</a> *node)</td></tr>
<tr class="separator:a54da5bb57bce5eb1f701b328cb771f5d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a27b996d5945c650d5214509bc64af4e3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a27b996d5945c650d5214509bc64af4e3">ForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a27b996d5945c650d5214509bc64af4e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a57f75a7d59e060a6dbb8350731647456"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a57f75a7d59e060a6dbb8350731647456">ForwardIterator</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&amp;it)=default</td></tr>
<tr class="separator:a57f75a7d59e060a6dbb8350731647456"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab3edf0f4d37b6d69f945a24c1b9c480d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#ab3edf0f4d37b6d69f945a24c1b9c480d">~ForwardIterator</a> ()=default</td></tr>
<tr class="separator:ab3edf0f4d37b6d69f945a24c1b9c480d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a806559c5fa0cafd62eee77d4c9c9cfb7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php">NodeBase</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a806559c5fa0cafd62eee77d4c9c9cfb7">getCurrent</a> ()</td></tr>
<tr class="separator:a806559c5fa0cafd62eee77d4c9c9cfb7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af7201503248008c0bc9efb2edd9438c9"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">Reference</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#af7201503248008c0bc9efb2edd9438c9">dereference</a> () const </td></tr>
<tr class="separator:af7201503248008c0bc9efb2edd9438c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a79c3cd6422ece562ac98e452eae5c543"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a79c3cd6422ece562ac98e452eae5c543">increment</a> ()</td></tr>
<tr class="separator:a79c3cd6422ece562ac98e452eae5c543"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa726f79f714220a29231586f9dbbde48"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#aa726f79f714220a29231586f9dbbde48">equal</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it) const </td></tr>
<tr class="separator:aa726f79f714220a29231586f9dbbde48"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56c8d7b07c782c805de74bd00b116ff7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a56c8d7b07c782c805de74bd00b116ff7">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> const &amp;it)=default</td></tr>
<tr class="separator:a56c8d7b07c782c805de74bd00b116ff7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a450ebaf32b70659fe08c8108a3af4675"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a450ebaf32b70659fe08c8108a3af4675">operator=</a> (<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> &amp;&amp;it)=default</td></tr>
<tr class="separator:a450ebaf32b70659fe08c8108a3af4675"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, class Category&gt;<br />
class NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt;</h3>

<p>Internal iterator for forward list. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a838077f8b3bb80dd60f04bf48c055e46"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a838077f8b3bb80dd60f04bf48c055e46">difference_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a1c1bc7527aad881dfe71782163ea9abd">DifferenceType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a1c1bc7527aad881dfe71782163ea9abd"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a1c1bc7527aad881dfe71782163ea9abd">DifferenceType</a> =  typename Traits::DifferenceType</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterator difference type </p>

</div>
</div>
<a class="anchor" id="a5a23e28633e49aa6450d2ca2f0e3510f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a5a23e28633e49aa6450d2ca2f0e3510f">iterator_category</a> =  typename Traits::iterator_category</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a75e3abc43993291c3a22a3825f7aae88"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a75e3abc43993291c3a22a3825f7aae88">Pointer</a> =  typename Traits::Pointer</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The pointer on iterated object </p>

</div>
</div>
<a class="anchor" id="ab62d03403d1822e891106e4a94dcc287"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#ab62d03403d1822e891106e4a94dcc287">pointer</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a75e3abc43993291c3a22a3825f7aae88">Pointer</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a307a8034c92c8f7b67745a08093097f2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">Reference</a> =  typename Traits::Reference</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The reference on iterated object </p>

</div>
</div>
<a class="anchor" id="ae4f322cf6dcbf1ba73fcbaa36822c4e6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#ae4f322cf6dcbf1ba73fcbaa36822c4e6">reference</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">Reference</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a8ded24eb3c9d9bc29b950f7a2f026789"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a8ded24eb3c9d9bc29b950f7a2f026789">Traits</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits.php">IteratorTraits</a>&lt;<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt;T, Category&gt;, T, Category&gt;</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inherited iterator traits </p>

</div>
</div>
<a class="anchor" id="a4bcca1d42c5ee414f0cca6685e080347"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a4bcca1d42c5ee414f0cca6685e080347">value_type</a> =  <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a57a8c0ce2d71e964d460def04051c777">ValueType</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>STL compatibility </p>

</div>
</div>
<a class="anchor" id="a57a8c0ce2d71e964d460def04051c777"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a57a8c0ce2d71e964d460def04051c777">ValueType</a> =  typename Traits::ValueType</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterated object </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a6f70da0e29614379e3a8de990f0c4b50"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor with nullptr node </p>

</div>
</div>
<a class="anchor" id="aed19d64a2569875c956fdd595cd8c183"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php">NodeBase</a> *&#160;</td>
          <td class="paramname"><em>node</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">node</td><td>the iterator node </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a54da5bb57bce5eb1f701b328cb771f5d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php">NodeBase</a> *&#160;</td>
          <td class="paramname"><em>node</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the iterator with the given node </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">node</td><td>the iterator node </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a27b996d5945c650d5214509bc64af4e3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a57f75a7d59e060a6dbb8350731647456"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab3edf0f4d37b6d69f945a24c1b9c480d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::~<a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php" title="Internal iterator for forward list. ">ForwardIterator</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="af7201503248008c0bc9efb2edd9438c9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">Reference</a> <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::dereference </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a reference on the iterated data </dd></dl>

</div>
</div>
<a class="anchor" id="aa726f79f714220a29231586f9dbbde48"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::equal </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if the given iterator point to the same position </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the other iterator </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a806559c5fa0cafd62eee77d4c9c9cfb7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_node_base.php">NodeBase</a>* <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::getCurrent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the current node </dd></dl>

</div>
</div>
<a class="anchor" id="a79c3cd6422ece562ac98e452eae5c543"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::increment </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Increment the iterator position by one </p>

</div>
</div>
<a class="anchor" id="a56c8d7b07c782c805de74bd00b116ff7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category &gt; const &amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a450ebaf32b70659fe08c8108a3af4675"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Category &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&amp; <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">NRE::Utility::Detail::ForwardListInner::ForwardIterator</a>&lt; T, Category &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php">ForwardIterator</a>&lt; T, Category &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>it</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of it into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">it</td><td>the iterator to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Utility/src/Utility/Detail/ForwardList/<a class="el" href="_detail_2_forward_list_2_n_r_e___forward_list_8hpp_source.php">NRE_ForwardList.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
