<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Class Members - Typedefs</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li class="current"><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_type.php#index_a"><span>a</span></a></li>
      <li><a href="functions_type_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_type_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_type_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_type_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_type_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_type_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_type_p.php#index_p"><span>p</span></a></li>
      <li class="current"><a href="functions_type_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_type_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_type_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_type_v.php#index_v"><span>v</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#afa251a0df0a73baae67d39177cfaa90f">NRE::Utility::Array&lt; T, Size &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#af84bc4ddbf660811caa74b1b1c7530f2">NRE::Utility::Array&lt; T, Size &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#ababffd6bcfcbd5c7f3a612af2b71453a">NRE::Utility::BasicString&lt; T &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a1ebb9b56406afd8fd5dae7cb88d4e8fb">NRE::Utility::BasicString&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a97b01e49e848ea33bd86878c241a23e2">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a88d757425005beea0b4a08bc3c6d2084">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#a307a8034c92c8f7b67745a08093097f2">NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#ae4f322cf6dcbf1ba73fcbaa36822c4e6">NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#abca2cde76036b8c728ca14b20dab8032">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#aa294cf06f45b64a5c3e43fabe2e12cd9">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#acd808453bbe076074bca6ba4a2d9a0c4">NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#aa727a09a1eca99861990ff60fd628f94">NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#af90a7a16e16cfd3cc79a0db9a145ee83">NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#ac36dfe5ac0e29d2315a18676aba3b132">NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#aba398717b3eb03287577e01414315379">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a7a64f445635cc96d63caf1ac27ea8622">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#a7631518ee078f3464da147c4d52d4868">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#aa2e440b6a1f92e80d3c350e43856f96f">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits_3_01_it_3_01_args_8_8_8_01_4_00_01_t_00_01_category_01_4.php#a5f751860a94ddc303784f5d9f2e81569">NRE::Utility::IteratorTraits&lt; It&lt; Args... &gt;, T, Category &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits_3_01_it_3_01_args_8_8_8_01_4_00_01_t_00_01_category_01_4.php#a808f9cd48084bc1603a85ad48a7a7236">NRE::Utility::IteratorTraits&lt; It&lt; Args... &gt;, T, Category &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a95e7b113a807277be45dcafc359ea816">NRE::Utility::Stack&lt; T, Container &gt;</a>
</li>
<li>reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#a876cb4a77abe21a9e67aae74cd668f2d">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>Reference
: <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#a77e2fccd2502fc1bfb9fee3dce6adde8">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>reverse_iterator
: <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#abfa8a6dff52fd8a068da221bca705e02">NRE::Utility::Array&lt; T, Size &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a4d9854c18ec08c4b445906f32c063aee">NRE::Utility::BasicString&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#a94c32d30b090c68244c77db1cd60a169">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#a7cfea7e0e61a9bab972756b6e01898d3">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>ReverseIterator
: <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a9f466da2cdfc8b3c07b9abf097d93acb">NRE::Utility::Array&lt; T, Size &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a417f6581726a0ad98b930909606d1212">NRE::Utility::BasicString&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#afa4905e29539752688529b811a7c86af">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#a16c079701562def37a47a652574d1350">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
