<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_a"><span>a</span></a></li>
      <li class="current"><a href="functions_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_b"></a>- b -</h3><ul>
<li>BasicString()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a9a3f02658ae8cb4aefeaebfd72b92020">NRE::Utility::BasicString&lt; T &gt;</a>
</li>
<li>beforeBegin()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a579eb48b0c0bcd298733dc0169ac1e5b">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
</li>
<li>begin()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a370a4e484cee21247a74334eef4d2b2d">NRE::Utility::Array&lt; T, Size &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a5bdd1cd2ef63b3fd7fd48e0e92e96d07">NRE::Utility::BasicString&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a15dc25ea23feecac337775e380a7279f">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#ac9d42d2fbe0444666e8fdf5aca0bfdb9">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a128c090b771811df3cdcade53d9e1b50">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#a1abe614a22ed274e9ebac84e520c3524">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#a1c9ededf87047f24fa5a7726f9612e26">NRE::Utility::Observable</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#aae759805a397f1e53d813386a6b4fcba">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>BucketEntry()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry.php#a61fe57baa0e79674bf13e09f6551cb94">NRE::Utility::Detail::HashTableInner::BucketEntry&lt; ValueType, StoreHash &gt;</a>
</li>
<li>bucketHashEquals()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash.php#ae266a9109d5ab3a704f091742b9516f3">NRE::Utility::Detail::HashTableInner::BucketEntryHash&lt; StoreHash &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_bucket_entry_hash_3_01true_01_4.php#af9cf0332d8568699af57b0ea73be64dc">NRE::Utility::Detail::HashTableInner::BucketEntryHash&lt; true &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
