<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Utility: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_a"><span>a</span></a></li>
      <li><a href="functions_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li class="current"><a href="functions_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>emplace()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#aee8cbf275f9663a31c8aae6efa00795f">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a650a2fa0b45abda6f6fdacec275a1fb5">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#abcadcf54eacb239586f40c09fb0d97f5">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_stack.php#a7056eedccf0985dfc6b83811373765ae">NRE::Utility::Stack&lt; T, Container &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#a04a8cca783c737ce4f271fd42eb3e24b">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>emplaceAfter()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a2a736c06f7e063a2e949cc2665264ea4">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
</li>
<li>emplaceBack()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#ae8b416315bae841565efbf9c23e668f8">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#ae70c6300a4d0facb7cf3232d2ab11ce0">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>emplaceFront()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a040cba4649e47a2f038b59c5e42aed01">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
</li>
<li>emplaceHint()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#acbe1bbfa60766a78830d63d4d80eb530">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a0ae616a891acd496526a50628c557e51">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
</li>
<li>end()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_array.php#a0e8f848bcb413ba1ed1c2285e3a88245">NRE::Utility::Array&lt; T, Size &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a40d0473b2964f19ba6f4a98696cc91b2">NRE::Utility::BasicString&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a8c4dea70121345a48362b2df83fcd9ca">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#a3d557392013624fceb5b509838b38413">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a0d641df832ffd4119293d3e5c5890d98">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#a2c3f2ffdf73b574662795a0fc6512b9c">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_observable.php#afc048fdbf499f9ed0a3e5b00e9249891">NRE::Utility::Observable</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#ab0ad64f96eee06c352dd4bdad7cf6488">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>endsWith()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#a477dbc8a44874807dd41a2d8b91ec14b">NRE::Utility::BasicString&lt; T &gt;</a>
</li>
<li>equal()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list_inner_1_1_forward_iterator.php#aa726f79f714220a29231586f9dbbde48">NRE::Utility::Detail::ForwardListInner::ForwardIterator&lt; T, Category &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_forward_iterator.php#a5315f9dec5de449954919e12ec89b861">NRE::Utility::Detail::HashTableInner::ForwardIterator&lt; T, Category, Bucket &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table_inner_1_1_local_forward_iterator.php#a245980557bc3105393f16a1f33904338">NRE::Utility::Detail::HashTableInner::LocalForwardIterator&lt; T, Category, Bucket &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_iterator_traits_3_01_it_3_01_args_8_8_8_01_4_00_01_t_00_01_category_01_4.php#afcbccad2752950750f002f3ab8666d6c">NRE::Utility::IteratorBase&lt; It&lt; Args... &gt;, T, Category &gt;</a>
</li>
<li>equalRange()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#ae039d19bc1d6960873e50da2b0c8865e">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a169c821d87f19e223630e55b251b6370">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
</li>
<li>erase()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_basic_string.php#aefa48bb2f2b634ef7661880d2757d3e4">NRE::Utility::BasicString&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_hash_table.php#a6dc2389a5ed46f52877faa975f51a597">NRE::Utility::Detail::HashTable&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_unordered_map.php#a9ae3b948aaf83570097dc9d18ac5df04">NRE::Utility::Detail::UnorderedMap&lt; Key, T, Allocator, StoreHash, Hash, KeyEqual &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_vector.php#a3c485155d0937170d9f0d8b437f34682">NRE::Utility::Detail::Vector&lt; T, Allocator &gt;</a>
, <a class="el" href="class_n_r_e_1_1_utility_1_1_static_vector.php#a85589a8ed16b98f47e880e3cf42e65b3">NRE::Utility::StaticVector&lt; T, Size &gt;</a>
</li>
<li>eraseAfter()
: <a class="el" href="class_n_r_e_1_1_utility_1_1_detail_1_1_forward_list.php#a16955b85b668a200c7eb5f22c036f66c">NRE::Utility::Detail::ForwardList&lt; T, Allocator &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
